/*
 * Copyright (c) 2017 Broadcom Limited
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief ARM system fatal error handler for Cortex-A
 *
 * This module provides the z_SysFatalErrorHandler() routine for Cortex-A
 * platforms.
 */

#include <kernel.h>
#include <toolchain.h>
#include <linker/sections.h>
#include <kernel_structs.h>
#include <misc/printk.h>

extern NANO_ESF _default_esf;

/**
 *
 * @brief Fatal error handler
 *
 * This routine implements the corrective action to be taken when the system
 * detects a fatal error.
 *
 * This sample implementation attempts to abort the current thread and allow
 * the system to continue executing, which may permit the system to continue
 * functioning with degraded capabilities.
 *
 * System designers may wish to enhance or substitute this sample
 * implementation to take other actions, such as logging error (or debug)
 * information to a persistent repository and/or rebooting the system.
 *
 * @param reason fatal error reason
 * @param pEsf pointer to exception stack frame
 *
 * @return N/A
 */
void __weak z_SysFatalErrorHandler(unsigned int reason,
					 const NANO_ESF *pEsf)
{
	u32_t i;

	ARG_UNUSED(pEsf);

#if !defined(CONFIG_SIMPLE_FATAL_ERROR_HANDLER)
#ifdef CONFIG_STACK_SENTINEL
	if (reason == _NANO_ERR_STACK_CHK_FAIL) {
		goto hang_system;
	}
#endif
	if (reason == _NANO_ERR_KERNEL_PANIC) {
		goto hang_system;
	}

	/* Check if we ended up here due an abort or undef instr. exception
	 * generated by a thread (SPSR mode == system mode). If yes, then we
	 * can return out of here so that only the thread in question is aborted
	 * while the system can continue to run.
	 */
	if (z_GetSavedCpuMode() != CPU_MODE_SYS) {
		printk("Fatal fault in ISR! Spinning...\n");
		goto hang_system;
	}
	/* Spin if this is an essential thread that caused the abort */
	if (z_is_thread_essential()) {
		printk("Fatal fault in essential thread! Spinning...\n");
		goto hang_system;
	}
	printk("Fatal fault in thread %p! Aborting.\n", _current);
	k_thread_abort(_current);

	/* Reset esf if _default_esf was passed
	 * This will ensure that default_esf does not hold any stale
	 * data. If the caller to z_SysFatalErrorHandler is unable to
	 * populate the esf, then the caller can choose to just pass
	 * the _default_esf without initializing it, in which case it
	 * is important that the esf state is reset.
	 */
	if (&_default_esf == pEsf) {
		for (i = 0; i < (sizeof(_default_esf) >> 2); i++) {
			*((u32_t *)pEsf + i) = 0xdeaddead;
		}
	}

	return;

hang_system:
#else
	ARG_UNUSED(reason);
#endif

	for (;;) {
		k_cpu_idle();
	}
	CODE_UNREACHABLE;
}
