obj-y += qspi_bcm58202.o
obj-y += qspi_bcm58202_macronix.o
obj-y += qspi_bcm58202_spansion.o
obj-y += qspi_bcm58202_micron.o
obj-y += qspi_bcm58202_giga_device.o
obj-y += qspi_bcm58202_xmc.o
obj-y += qspi_bcm58202_winbond.o
obj-y += qspi_memcpy_src_unaligned.o

-include $(MPOS_BASE)/Makefile.inc
