/******************************************************************************
 *  Copyright (c) 2005-2018 Broadcom. All Rights Reserved. The term "Broadcom"
 *  refers to Broadcom Inc. and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the
 *  terms and conditions of a separate, written license agreement executed
 *  between you and Broadcom (an "Authorized License").  Except as set forth in
 *  an Authorized License, Broadcom grants no license (express or implied),
 *  right to use, or waiver of any kind with respect to the Software, and
 *  Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE,
 *  THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 *  IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization,
 *  constitutes the valuable trade secrets of Broadcom, and you shall use all
 *  reasonable efforts to protect the confidentiality thereof, and to use this
 *  information only in connection with your use of Broadcom integrated circuit
 *  products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 *  "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 *  OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 *  RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 *  IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *  PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *  ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE
 *  ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
 *  ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 *  INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 *  RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 *  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 *  EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 *  WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 *  FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/

/*
 * @file bbl_regs.h
 * @brief BBL register addresses and bit fields
 */

#ifndef __BBL_REGS_H__
#define __BBL_REGS_H__

#define BBL_RTC_PER 0x00000000
#define BBL_RTC_PER_BASE 0x000
#define BBL_RTC_PER__BBL_PER_L 11
#define BBL_RTC_PER__BBL_PER_R 0
#define BBL_RTC_PER__BBL_PER_WIDTH 12
#define BBL_RTC_PER__BBL_PER_RESETVALUE 0x000
#define BBL_RTC_PER__RESERVED_L 31
#define BBL_RTC_PER__RESERVED_R 12
#define BBL_RTC_PER_WIDTH 12
#define BBL_RTC_PER__WIDTH 12
#define BBL_RTC_PER_ALL_L 11
#define BBL_RTC_PER_ALL_R 0
#define BBL_RTC_PER__ALL_L 11
#define BBL_RTC_PER__ALL_R 0
#define BBL_RTC_PER_DATAMASK 0x00000fff
#define BBL_RTC_PER_RESETVALUE 0x0
#define BBL_RTC_MATCH 0x00000004
#define BBL_RTC_MATCH_BASE 0x004
#define BBL_RTC_MATCH__BBL_MATCH_L 15
#define BBL_RTC_MATCH__BBL_MATCH_R 0
#define BBL_RTC_MATCH__BBL_MATCH_WIDTH 16
#define BBL_RTC_MATCH__BBL_MATCH_RESETVALUE 0xffff
#define BBL_RTC_MATCH__RESERVED_L 31
#define BBL_RTC_MATCH__RESERVED_R 16
#define BBL_RTC_MATCH_WIDTH 16
#define BBL_RTC_MATCH__WIDTH 16
#define BBL_RTC_MATCH_ALL_L 15
#define BBL_RTC_MATCH_ALL_R 0
#define BBL_RTC_MATCH__ALL_L 15
#define BBL_RTC_MATCH__ALL_R 0
#define BBL_RTC_MATCH_DATAMASK 0x0000ffff
#define BBL_RTC_MATCH_RESETVALUE 0xffff
#define BBL_RTC_DIV 0x00000008
#define BBL_RTC_DIV_BASE 0x008
#define BBL_RTC_DIV__BBL_RTC_DIV_L 14
#define BBL_RTC_DIV__BBL_RTC_DIV_R 0
#define BBL_RTC_DIV__BBL_RTC_DIV_WIDTH 15
#define BBL_RTC_DIV__BBL_RTC_DIV_RESETVALUE 0x0
#define BBL_RTC_DIV__RESERVED_L 31
#define BBL_RTC_DIV__RESERVED_R 15
#define BBL_RTC_DIV_WIDTH 15
#define BBL_RTC_DIV__WIDTH 15
#define BBL_RTC_DIV_ALL_L 14
#define BBL_RTC_DIV_ALL_R 0
#define BBL_RTC_DIV__ALL_L 14
#define BBL_RTC_DIV__ALL_R 0
#define BBL_RTC_DIV_DATAMASK 0x00007fff
#define BBL_RTC_DIV_RESETVALUE 0x0
#define BBL_RTC_SECOND 0x0000000c
#define BBL_RTC_SECOND_BASE 0x00c
#define BBL_RTC_SECOND__BBL_RTC_SECONDS_L 31
#define BBL_RTC_SECOND__BBL_RTC_SECONDS_R 0
#define BBL_RTC_SECOND__BBL_RTC_SECONDS_WIDTH 32
#define BBL_RTC_SECOND__BBL_RTC_SECONDS_RESETVALUE 0x00000000
#define BBL_RTC_SECOND_WIDTH 32
#define BBL_RTC_SECOND__WIDTH 32
#define BBL_RTC_SECOND_ALL_L 31
#define BBL_RTC_SECOND_ALL_R 0
#define BBL_RTC_SECOND__ALL_L 31
#define BBL_RTC_SECOND__ALL_R 0
#define BBL_RTC_SECOND_DATAMASK 0xffffffff
#define BBL_RTC_SECOND_RESETVALUE 0x0
#define BBL_INTERRUPT_EN 0x00000010
#define BBL_INTERRUPT_EN_BASE 0x010
#define BBL_INTERRUPT_EN__bbl_raw_tamper_intr_en_L 7
#define BBL_INTERRUPT_EN__bbl_raw_tamper_intr_en_R 7
#define BBL_INTERRUPT_EN__bbl_raw_tamper_intr_en 7
#define BBL_INTERRUPT_EN__bbl_raw_tamper_intr_en_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_raw_tamper_intr_en_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_tampern_intr_en_L 6
#define BBL_INTERRUPT_EN__bbl_tampern_intr_en_R 6
#define BBL_INTERRUPT_EN__bbl_tampern_intr_en 6
#define BBL_INTERRUPT_EN__bbl_tampern_intr_en_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_tampern_intr_en_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en0_L 5
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en0_R 5
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en0 5
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en0_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en0_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en1_L 4
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en1_R 4
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en1 4
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en1_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_tamperin_p_intr_en1_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en0_L 3
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en0_R 3
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en0 3
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en0_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en0_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en1_L 2
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en1_R 2
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en1 2
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en1_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_tamperin_n_intr_en1_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_match_intr_en_L 1
#define BBL_INTERRUPT_EN__bbl_match_intr_en_R 1
#define BBL_INTERRUPT_EN__bbl_match_intr_en 1
#define BBL_INTERRUPT_EN__bbl_match_intr_en_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_match_intr_en_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__bbl_period_intr_en_L 0
#define BBL_INTERRUPT_EN__bbl_period_intr_en_R 0
#define BBL_INTERRUPT_EN__bbl_period_intr_en 0
#define BBL_INTERRUPT_EN__bbl_period_intr_en_WIDTH 1
#define BBL_INTERRUPT_EN__bbl_period_intr_en_RESETVALUE 0x0
#define BBL_INTERRUPT_EN__RESERVED_L 31
#define BBL_INTERRUPT_EN__RESERVED_R 8
#define BBL_INTERRUPT_EN_WIDTH 8
#define BBL_INTERRUPT_EN__WIDTH 8
#define BBL_INTERRUPT_EN_ALL_L 7
#define BBL_INTERRUPT_EN_ALL_R 0
#define BBL_INTERRUPT_EN__ALL_L 7
#define BBL_INTERRUPT_EN__ALL_R 0
#define BBL_INTERRUPT_EN_DATAMASK 0x000000ff
#define BBL_INTERRUPT_EN_RESETVALUE 0x0
#define BBL_INTERRUPT_stat 0x00000014
#define BBL_INTERRUPT_stat_BASE 0x014
#define BBL_INTERRUPT_stat__bbl_raw_tamper_intr_sts_L 7
#define BBL_INTERRUPT_stat__bbl_raw_tamper_intr_sts_R 7
#define BBL_INTERRUPT_stat__bbl_raw_tamper_intr_sts 7
#define BBL_INTERRUPT_stat__bbl_raw_tamper_intr_sts_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_raw_tamper_intr_sts_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_tampern_intr_sts_L 6
#define BBL_INTERRUPT_stat__bbl_tampern_intr_sts_R 6
#define BBL_INTERRUPT_stat__bbl_tampern_intr_sts 6
#define BBL_INTERRUPT_stat__bbl_tampern_intr_sts_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_tampern_intr_sts_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts0_L 5
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts0_R 5
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts0 5
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts0_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts0_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts1_L 4
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts1_R 4
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts1 4
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts1_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_tamperin_p_intr_sts1_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts0_L 3
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts0_R 3
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts0 3
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts0_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts0_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts1_L 2
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts1_R 2
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts1 2
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts1_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_tamperin_n_intr_sts1_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_match_intr_sts_L 1
#define BBL_INTERRUPT_stat__bbl_match_intr_sts_R 1
#define BBL_INTERRUPT_stat__bbl_match_intr_sts 1
#define BBL_INTERRUPT_stat__bbl_match_intr_sts_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_match_intr_sts_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__bbl_period_intr_sts_L 0
#define BBL_INTERRUPT_stat__bbl_period_intr_sts_R 0
#define BBL_INTERRUPT_stat__bbl_period_intr_sts 0
#define BBL_INTERRUPT_stat__bbl_period_intr_sts_WIDTH 1
#define BBL_INTERRUPT_stat__bbl_period_intr_sts_RESETVALUE 0x0
#define BBL_INTERRUPT_stat__RESERVED_L 31
#define BBL_INTERRUPT_stat__RESERVED_R 8
#define BBL_INTERRUPT_stat_WIDTH 8
#define BBL_INTERRUPT_stat__WIDTH 8
#define BBL_INTERRUPT_stat_ALL_L 7
#define BBL_INTERRUPT_stat_ALL_R 0
#define BBL_INTERRUPT_stat__ALL_L 7
#define BBL_INTERRUPT_stat__ALL_R 0
#define BBL_INTERRUPT_stat_DATAMASK 0x000000ff
#define BBL_INTERRUPT_stat_RESETVALUE 0x0
#define BBL_INTERRUPT_clr 0x00000018
#define BBL_INTERRUPT_clr_BASE 0x018
#define BBL_INTERRUPT_clr__bbl_raw_tamper_intr_clr_L 7
#define BBL_INTERRUPT_clr__bbl_raw_tamper_intr_clr_R 7
#define BBL_INTERRUPT_clr__bbl_raw_tamper_intr_clr 7
#define BBL_INTERRUPT_clr__bbl_raw_tamper_intr_clr_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_raw_tamper_intr_clr_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_tampern_intr_clr_L 6
#define BBL_INTERRUPT_clr__bbl_tampern_intr_clr_R 6
#define BBL_INTERRUPT_clr__bbl_tampern_intr_clr 6
#define BBL_INTERRUPT_clr__bbl_tampern_intr_clr_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_tampern_intr_clr_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr0_L 5
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr0_R 5
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr0 5
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr0_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr0_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr1_L 4
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr1_R 4
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr1 4
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr1_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_tamper_P_intr_clr1_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr0_L 3
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr0_R 3
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr0 3
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr0_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr0_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr1_L 2
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr1_R 2
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr1 2
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr1_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_tamper_N_intr_clr1_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_match_intr_clr_L 1
#define BBL_INTERRUPT_clr__bbl_match_intr_clr_R 1
#define BBL_INTERRUPT_clr__bbl_match_intr_clr 1
#define BBL_INTERRUPT_clr__bbl_match_intr_clr_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_match_intr_clr_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__bbl_period_intr_clr_L 0
#define BBL_INTERRUPT_clr__bbl_period_intr_clr_R 0
#define BBL_INTERRUPT_clr__bbl_period_intr_clr 0
#define BBL_INTERRUPT_clr__bbl_period_intr_clr_WIDTH 1
#define BBL_INTERRUPT_clr__bbl_period_intr_clr_RESETVALUE 0x0
#define BBL_INTERRUPT_clr__RESERVED_L 31
#define BBL_INTERRUPT_clr__RESERVED_R 8
#define BBL_INTERRUPT_clr_WIDTH 8
#define BBL_INTERRUPT_clr__WIDTH 8
#define BBL_INTERRUPT_clr_ALL_L 7
#define BBL_INTERRUPT_clr_ALL_R 0
#define BBL_INTERRUPT_clr__ALL_L 7
#define BBL_INTERRUPT_clr__ALL_R 0
#define BBL_INTERRUPT_clr_DATAMASK 0x000000ff
#define BBL_INTERRUPT_clr_RESETVALUE 0x0
#define BBL_CONTROL 0x0000001c
#define BBL_CONTROL_BASE 0x01c
#define BBL_CONTROL__bbl_rtc_stop_L 0
#define BBL_CONTROL__bbl_rtc_stop_R 0
#define BBL_CONTROL__bbl_rtc_stop 0
#define BBL_CONTROL__bbl_rtc_stop_WIDTH 1
#define BBL_CONTROL__bbl_rtc_stop_RESETVALUE 0x0
#define BBL_CONTROL__RESERVED_L 31
#define BBL_CONTROL__RESERVED_R 1
#define BBL_CONTROL_WIDTH 1
#define BBL_CONTROL__WIDTH 1
#define BBL_CONTROL_ALL_L 0
#define BBL_CONTROL_ALL_R 0
#define BBL_CONTROL__ALL_L 0
#define BBL_CONTROL__ALL_R 0
#define BBL_CONTROL_DATAMASK 0x00000001
#define BBL_CONTROL_RESETVALUE 0x0
#define BBL_TAMPER_TIMESTAMP 0x00000020
#define BBL_TAMPER_TIMESTAMP_BASE 0x020
#define BBL_TAMPER_TIMESTAMP__tamper_timestamp_L 31
#define BBL_TAMPER_TIMESTAMP__tamper_timestamp_R 0
#define BBL_TAMPER_TIMESTAMP__tamper_timestamp_WIDTH 32
#define BBL_TAMPER_TIMESTAMP__tamper_timestamp_RESETVALUE 0x00000000
#define BBL_TAMPER_TIMESTAMP_WIDTH 32
#define BBL_TAMPER_TIMESTAMP__WIDTH 32
#define BBL_TAMPER_TIMESTAMP_ALL_L 31
#define BBL_TAMPER_TIMESTAMP_ALL_R 0
#define BBL_TAMPER_TIMESTAMP__ALL_L 31
#define BBL_TAMPER_TIMESTAMP__ALL_R 0
#define BBL_TAMPER_TIMESTAMP_DATAMASK 0xffffffff
#define BBL_TAMPER_TIMESTAMP_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE 0x00000024
#define BBL_TAMPER_SRC_ENABLE_BASE 0x024
#define BBL_TAMPER_SRC_ENABLE__crmu_secdata_clr_evnet_en_L 29
#define BBL_TAMPER_SRC_ENABLE__crmu_secdata_clr_evnet_en_R 29
#define BBL_TAMPER_SRC_ENABLE__crmu_secdata_clr_evnet_en 29
#define BBL_TAMPER_SRC_ENABLE__crmu_secdata_clr_evnet_en_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE__crmu_secdata_clr_evnet_en_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_event_En_L 28
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_event_En_R 28
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_event_En 28
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_event_En_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_event_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_rst_En_L 27
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_rst_En_R 27
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_rst_En 27
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_rst_En_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE__BBL_spl_rst_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_Vmon_En_L 26
#define BBL_TAMPER_SRC_ENABLE__BBL_Vmon_En_R 26
#define BBL_TAMPER_SRC_ENABLE__BBL_Vmon_En 26
#define BBL_TAMPER_SRC_ENABLE__BBL_Vmon_En_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE__BBL_Vmon_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_Fmon_En_L 25
#define BBL_TAMPER_SRC_ENABLE__BBL_Fmon_En_R 24
#define BBL_TAMPER_SRC_ENABLE__BBL_Fmon_En_WIDTH 2
#define BBL_TAMPER_SRC_ENABLE__BBL_Fmon_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_Tmon_En_L 23
#define BBL_TAMPER_SRC_ENABLE__BBL_Tmon_En_R 21
#define BBL_TAMPER_SRC_ENABLE__BBL_Tmon_En_WIDTH 3
#define BBL_TAMPER_SRC_ENABLE__BBL_Tmon_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_IGrid_En_L 20
#define BBL_TAMPER_SRC_ENABLE__BBL_IGrid_En_R 20
#define BBL_TAMPER_SRC_ENABLE__BBL_IGrid_En 20
#define BBL_TAMPER_SRC_ENABLE__BBL_IGrid_En_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE__BBL_IGrid_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_Egrid_En_L 19
#define BBL_TAMPER_SRC_ENABLE__BBL_Egrid_En_R 18
#define BBL_TAMPER_SRC_ENABLE__BBL_Egrid_En_WIDTH 2
#define BBL_TAMPER_SRC_ENABLE__BBL_Egrid_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__BBL_Tamperpin_En_L 17
#define BBL_TAMPER_SRC_ENABLE__BBL_Tamperpin_En_R 0
#define BBL_TAMPER_SRC_ENABLE__BBL_Tamperpin_En_WIDTH 18
#define BBL_TAMPER_SRC_ENABLE__BBL_Tamperpin_En_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE__RESERVED_L 31
#define BBL_TAMPER_SRC_ENABLE__RESERVED_R 30
#define BBL_TAMPER_SRC_ENABLE_WIDTH 30
#define BBL_TAMPER_SRC_ENABLE__WIDTH 30
#define BBL_TAMPER_SRC_ENABLE_ALL_L 29
#define BBL_TAMPER_SRC_ENABLE_ALL_R 0
#define BBL_TAMPER_SRC_ENABLE__ALL_L 29
#define BBL_TAMPER_SRC_ENABLE__ALL_R 0
#define BBL_TAMPER_SRC_ENABLE_DATAMASK 0x3fffffff
#define BBL_TAMPER_SRC_ENABLE_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT 0x00000028
#define BBL_TAMPER_SRC_STAT_BASE 0x028
#define BBL_TAMPER_SRC_STAT__crmu_secdata_clr_evnet_sts_L 29
#define BBL_TAMPER_SRC_STAT__crmu_secdata_clr_evnet_sts_R 29
#define BBL_TAMPER_SRC_STAT__crmu_secdata_clr_evnet_sts 29
#define BBL_TAMPER_SRC_STAT__crmu_secdata_clr_evnet_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT__crmu_secdata_clr_evnet_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_spl_event_sts_L 28
#define BBL_TAMPER_SRC_STAT__BBL_spl_event_sts_R 28
#define BBL_TAMPER_SRC_STAT__BBL_spl_event_sts 28
#define BBL_TAMPER_SRC_STAT__BBL_spl_event_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT__BBL_spl_event_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_spl_rst_sts_L 27
#define BBL_TAMPER_SRC_STAT__BBL_spl_rst_sts_R 27
#define BBL_TAMPER_SRC_STAT__BBL_spl_rst_sts 27
#define BBL_TAMPER_SRC_STAT__BBL_spl_rst_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT__BBL_spl_rst_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_Vmon_sts_L 26
#define BBL_TAMPER_SRC_STAT__BBL_Vmon_sts_R 26
#define BBL_TAMPER_SRC_STAT__BBL_Vmon_sts 26
#define BBL_TAMPER_SRC_STAT__BBL_Vmon_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT__BBL_Vmon_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_Fmon_sts_L 25
#define BBL_TAMPER_SRC_STAT__BBL_Fmon_sts_R 24
#define BBL_TAMPER_SRC_STAT__BBL_Fmon_sts_WIDTH 2
#define BBL_TAMPER_SRC_STAT__BBL_Fmon_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_Tmon_sts_L 23
#define BBL_TAMPER_SRC_STAT__BBL_Tmon_sts_R 21
#define BBL_TAMPER_SRC_STAT__BBL_Tmon_sts_WIDTH 3
#define BBL_TAMPER_SRC_STAT__BBL_Tmon_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_IGrid_sts_L 20
#define BBL_TAMPER_SRC_STAT__BBL_IGrid_sts_R 20
#define BBL_TAMPER_SRC_STAT__BBL_IGrid_sts 20
#define BBL_TAMPER_SRC_STAT__BBL_IGrid_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT__BBL_IGrid_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_Egrid_sts_L 19
#define BBL_TAMPER_SRC_STAT__BBL_Egrid_sts_R 18
#define BBL_TAMPER_SRC_STAT__BBL_Egrid_sts_WIDTH 2
#define BBL_TAMPER_SRC_STAT__BBL_Egrid_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__BBL_Tamperpin_sts_L 17
#define BBL_TAMPER_SRC_STAT__BBL_Tamperpin_sts_R 0
#define BBL_TAMPER_SRC_STAT__BBL_Tamperpin_sts_WIDTH 18
#define BBL_TAMPER_SRC_STAT__BBL_Tamperpin_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT__RESERVED_L 31
#define BBL_TAMPER_SRC_STAT__RESERVED_R 30
#define BBL_TAMPER_SRC_STAT_WIDTH 30
#define BBL_TAMPER_SRC_STAT__WIDTH 30
#define BBL_TAMPER_SRC_STAT_ALL_L 29
#define BBL_TAMPER_SRC_STAT_ALL_R 0
#define BBL_TAMPER_SRC_STAT__ALL_L 29
#define BBL_TAMPER_SRC_STAT__ALL_R 0
#define BBL_TAMPER_SRC_STAT_DATAMASK 0x3fffffff
#define BBL_TAMPER_SRC_STAT_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR 0x0000002c
#define BBL_TAMPER_SRC_CLEAR_BASE 0x02c
#define BBL_TAMPER_SRC_CLEAR__crmu_secdata_clr_evnet_clr_L 29
#define BBL_TAMPER_SRC_CLEAR__crmu_secdata_clr_evnet_clr_R 29
#define BBL_TAMPER_SRC_CLEAR__crmu_secdata_clr_evnet_clr 29
#define BBL_TAMPER_SRC_CLEAR__crmu_secdata_clr_evnet_clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR__crmu_secdata_clr_evnet_clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_event_Clr_L 28
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_event_Clr_R 28
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_event_Clr 28
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_event_Clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_event_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_rst_Clr_L 27
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_rst_Clr_R 27
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_rst_Clr 27
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_rst_Clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR__BBL_spl_rst_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_Vmon_Clr_L 26
#define BBL_TAMPER_SRC_CLEAR__BBL_Vmon_Clr_R 26
#define BBL_TAMPER_SRC_CLEAR__BBL_Vmon_Clr 26
#define BBL_TAMPER_SRC_CLEAR__BBL_Vmon_Clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR__BBL_Vmon_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_Fmon_Clr_L 25
#define BBL_TAMPER_SRC_CLEAR__BBL_Fmon_Clr_R 24
#define BBL_TAMPER_SRC_CLEAR__BBL_Fmon_Clr_WIDTH 2
#define BBL_TAMPER_SRC_CLEAR__BBL_Fmon_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_Tmon_Clr_L 23
#define BBL_TAMPER_SRC_CLEAR__BBL_Tmon_Clr_R 21
#define BBL_TAMPER_SRC_CLEAR__BBL_Tmon_Clr_WIDTH 3
#define BBL_TAMPER_SRC_CLEAR__BBL_Tmon_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_IGrid_Clr_L 20
#define BBL_TAMPER_SRC_CLEAR__BBL_IGrid_Clr_R 20
#define BBL_TAMPER_SRC_CLEAR__BBL_IGrid_Clr 20
#define BBL_TAMPER_SRC_CLEAR__BBL_IGrid_Clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR__BBL_IGrid_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_Egrid_Clr_L 19
#define BBL_TAMPER_SRC_CLEAR__BBL_Egrid_Clr_R 18
#define BBL_TAMPER_SRC_CLEAR__BBL_Egrid_Clr_WIDTH 2
#define BBL_TAMPER_SRC_CLEAR__BBL_Egrid_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__BBL_Tamperpin_Clr_L 17
#define BBL_TAMPER_SRC_CLEAR__BBL_Tamperpin_Clr_R 0
#define BBL_TAMPER_SRC_CLEAR__BBL_Tamperpin_Clr_WIDTH 18
#define BBL_TAMPER_SRC_CLEAR__BBL_Tamperpin_Clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR__RESERVED_L 31
#define BBL_TAMPER_SRC_CLEAR__RESERVED_R 30
#define BBL_TAMPER_SRC_CLEAR_WIDTH 30
#define BBL_TAMPER_SRC_CLEAR__WIDTH 30
#define BBL_TAMPER_SRC_CLEAR_ALL_L 29
#define BBL_TAMPER_SRC_CLEAR_ALL_R 0
#define BBL_TAMPER_SRC_CLEAR__ALL_L 29
#define BBL_TAMPER_SRC_CLEAR__ALL_R 0
#define BBL_TAMPER_SRC_CLEAR_DATAMASK 0x3fffffff
#define BBL_TAMPER_SRC_CLEAR_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE_1 0x00000030
#define BBL_TAMPER_SRC_ENABLE_1_BASE 0x030
#define BBL_TAMPER_SRC_ENABLE_1__vmon_cmp_data_tamper_en_L 2
#define BBL_TAMPER_SRC_ENABLE_1__vmon_cmp_data_tamper_en_R 2
#define BBL_TAMPER_SRC_ENABLE_1__vmon_cmp_data_tamper_en 2
#define BBL_TAMPER_SRC_ENABLE_1__vmon_cmp_data_tamper_en_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE_1__vmon_cmp_data_tamper_en_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE_1__hvd_n_tamper_en_L 1
#define BBL_TAMPER_SRC_ENABLE_1__hvd_n_tamper_en_R 1
#define BBL_TAMPER_SRC_ENABLE_1__hvd_n_tamper_en 1
#define BBL_TAMPER_SRC_ENABLE_1__hvd_n_tamper_en_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE_1__hvd_n_tamper_en_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE_1__ecc_tamper_en_L 0
#define BBL_TAMPER_SRC_ENABLE_1__ecc_tamper_en_R 0
#define BBL_TAMPER_SRC_ENABLE_1__ecc_tamper_en 0
#define BBL_TAMPER_SRC_ENABLE_1__ecc_tamper_en_WIDTH 1
#define BBL_TAMPER_SRC_ENABLE_1__ecc_tamper_en_RESETVALUE 0x0
#define BBL_TAMPER_SRC_ENABLE_1__RESERVED_L 31
#define BBL_TAMPER_SRC_ENABLE_1__RESERVED_R 3
#define BBL_TAMPER_SRC_ENABLE_1_WIDTH 3
#define BBL_TAMPER_SRC_ENABLE_1__WIDTH 3
#define BBL_TAMPER_SRC_ENABLE_1_ALL_L 2
#define BBL_TAMPER_SRC_ENABLE_1_ALL_R 0
#define BBL_TAMPER_SRC_ENABLE_1__ALL_L 2
#define BBL_TAMPER_SRC_ENABLE_1__ALL_R 0
#define BBL_TAMPER_SRC_ENABLE_1_DATAMASK 0x00000007
#define BBL_TAMPER_SRC_ENABLE_1_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT_1 0x00000034
#define BBL_TAMPER_SRC_STAT_1_BASE 0x034
#define BBL_TAMPER_SRC_STAT_1__vmon_cmp_data_tamper_sts_L 2
#define BBL_TAMPER_SRC_STAT_1__vmon_cmp_data_tamper_sts_R 2
#define BBL_TAMPER_SRC_STAT_1__vmon_cmp_data_tamper_sts 2
#define BBL_TAMPER_SRC_STAT_1__vmon_cmp_data_tamper_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT_1__vmon_cmp_data_tamper_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT_1__hvd_n_tamper_sts_L 1
#define BBL_TAMPER_SRC_STAT_1__hvd_n_tamper_sts_R 1
#define BBL_TAMPER_SRC_STAT_1__hvd_n_tamper_sts 1
#define BBL_TAMPER_SRC_STAT_1__hvd_n_tamper_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT_1__hvd_n_tamper_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT_1__ecc_tamper_sts_L 0
#define BBL_TAMPER_SRC_STAT_1__ecc_tamper_sts_R 0
#define BBL_TAMPER_SRC_STAT_1__ecc_tamper_sts 0
#define BBL_TAMPER_SRC_STAT_1__ecc_tamper_sts_WIDTH 1
#define BBL_TAMPER_SRC_STAT_1__ecc_tamper_sts_RESETVALUE 0x0
#define BBL_TAMPER_SRC_STAT_1__RESERVED_L 31
#define BBL_TAMPER_SRC_STAT_1__RESERVED_R 3
#define BBL_TAMPER_SRC_STAT_1_WIDTH 3
#define BBL_TAMPER_SRC_STAT_1__WIDTH 3
#define BBL_TAMPER_SRC_STAT_1_ALL_L 2
#define BBL_TAMPER_SRC_STAT_1_ALL_R 0
#define BBL_TAMPER_SRC_STAT_1__ALL_L 2
#define BBL_TAMPER_SRC_STAT_1__ALL_R 0
#define BBL_TAMPER_SRC_STAT_1_DATAMASK 0x00000007
#define BBL_TAMPER_SRC_STAT_1_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR_1 0x00000038
#define BBL_TAMPER_SRC_CLEAR_1_BASE 0x038
#define BBL_TAMPER_SRC_CLEAR_1__vmon_cmp_data_tamper_clr_L 2
#define BBL_TAMPER_SRC_CLEAR_1__vmon_cmp_data_tamper_clr_R 2
#define BBL_TAMPER_SRC_CLEAR_1__vmon_cmp_data_tamper_clr 2
#define BBL_TAMPER_SRC_CLEAR_1__vmon_cmp_data_tamper_clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR_1__vmon_cmp_data_tamper_clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR_1__hvd_n_tamper_clr_L 1
#define BBL_TAMPER_SRC_CLEAR_1__hvd_n_tamper_clr_R 1
#define BBL_TAMPER_SRC_CLEAR_1__hvd_n_tamper_clr 1
#define BBL_TAMPER_SRC_CLEAR_1__hvd_n_tamper_clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR_1__hvd_n_tamper_clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR_1__ecc_tamper_clr_L 0
#define BBL_TAMPER_SRC_CLEAR_1__ecc_tamper_clr_R 0
#define BBL_TAMPER_SRC_CLEAR_1__ecc_tamper_clr 0
#define BBL_TAMPER_SRC_CLEAR_1__ecc_tamper_clr_WIDTH 1
#define BBL_TAMPER_SRC_CLEAR_1__ecc_tamper_clr_RESETVALUE 0x0
#define BBL_TAMPER_SRC_CLEAR_1__RESERVED_L 31
#define BBL_TAMPER_SRC_CLEAR_1__RESERVED_R 3
#define BBL_TAMPER_SRC_CLEAR_1_WIDTH 3
#define BBL_TAMPER_SRC_CLEAR_1__WIDTH 3
#define BBL_TAMPER_SRC_CLEAR_1_ALL_L 2
#define BBL_TAMPER_SRC_CLEAR_1_ALL_R 0
#define BBL_TAMPER_SRC_CLEAR_1__ALL_L 2
#define BBL_TAMPER_SRC_CLEAR_1__ALL_R 0
#define BBL_TAMPER_SRC_CLEAR_1_DATAMASK 0x00000007
#define BBL_TAMPER_SRC_CLEAR_1_RESETVALUE 0x0
#define BBL_GLITCH_CFG 0x0000003c
#define BBL_GLITCH_CFG_BASE 0x03c
#define BBL_GLITCH_CFG__enable_glitchfilt_L 8
#define BBL_GLITCH_CFG__enable_glitchfilt_R 0
#define BBL_GLITCH_CFG__enable_glitchfilt_WIDTH 9
#define BBL_GLITCH_CFG__enable_glitchfilt_RESETVALUE 0x1
#define BBL_GLITCH_CFG__RESERVED_L 31
#define BBL_GLITCH_CFG__RESERVED_R 9
#define BBL_GLITCH_CFG_WIDTH 9
#define BBL_GLITCH_CFG__WIDTH 9
#define BBL_GLITCH_CFG_ALL_L 8
#define BBL_GLITCH_CFG_ALL_R 0
#define BBL_GLITCH_CFG__ALL_L 8
#define BBL_GLITCH_CFG__ALL_R 0
#define BBL_GLITCH_CFG_DATAMASK 0x000001ff
#define BBL_GLITCH_CFG_RESETVALUE 0x1
#define BBL_EN_TAMPERIN 0x00000040
#define BBL_EN_TAMPERIN_BASE 0x040
#define BBL_EN_TAMPERIN__en_tamperin_L 8
#define BBL_EN_TAMPERIN__en_tamperin_R 0
#define BBL_EN_TAMPERIN__en_tamperin_WIDTH 9
#define BBL_EN_TAMPERIN__en_tamperin_RESETVALUE 0x1
#define BBL_EN_TAMPERIN__RESERVED_L 31
#define BBL_EN_TAMPERIN__RESERVED_R 9
#define BBL_EN_TAMPERIN_WIDTH 9
#define BBL_EN_TAMPERIN__WIDTH 9
#define BBL_EN_TAMPERIN_ALL_L 8
#define BBL_EN_TAMPERIN_ALL_R 0
#define BBL_EN_TAMPERIN__ALL_L 8
#define BBL_EN_TAMPERIN__ALL_R 0
#define BBL_EN_TAMPERIN_DATAMASK 0x000001ff
#define BBL_EN_TAMPERIN_RESETVALUE 0x1
#define BBL_EMESH_CONFIG 0x00000044
#define BBL_EMESH_CONFIG_BASE 0x044
#define BBL_EMESH_CONFIG__bbl_mesh_clr_L 10
#define BBL_EMESH_CONFIG__bbl_mesh_clr_R 10
#define BBL_EMESH_CONFIG__bbl_mesh_clr 10
#define BBL_EMESH_CONFIG__bbl_mesh_clr_WIDTH 1
#define BBL_EMESH_CONFIG__bbl_mesh_clr_RESETVALUE 0x0
#define BBL_EMESH_CONFIG__en_extmesh_dyn_L 9
#define BBL_EMESH_CONFIG__en_extmesh_dyn_R 9
#define BBL_EMESH_CONFIG__en_extmesh_dyn 9
#define BBL_EMESH_CONFIG__en_extmesh_dyn_WIDTH 1
#define BBL_EMESH_CONFIG__en_extmesh_dyn_RESETVALUE 0x0
#define BBL_EMESH_CONFIG__en_extmesh_fc_L 8
#define BBL_EMESH_CONFIG__en_extmesh_fc_R 8
#define BBL_EMESH_CONFIG__en_extmesh_fc 8
#define BBL_EMESH_CONFIG__en_extmesh_fc_WIDTH 1
#define BBL_EMESH_CONFIG__en_extmesh_fc_RESETVALUE 0x0
#define BBL_EMESH_CONFIG__en_extmesh_L 7
#define BBL_EMESH_CONFIG__en_extmesh_R 0
#define BBL_EMESH_CONFIG__en_extmesh_WIDTH 8
#define BBL_EMESH_CONFIG__en_extmesh_RESETVALUE 0x00
#define BBL_EMESH_CONFIG__RESERVED_L 31
#define BBL_EMESH_CONFIG__RESERVED_R 11
#define BBL_EMESH_CONFIG_WIDTH 11
#define BBL_EMESH_CONFIG__WIDTH 11
#define BBL_EMESH_CONFIG_ALL_L 10
#define BBL_EMESH_CONFIG_ALL_R 0
#define BBL_EMESH_CONFIG__ALL_L 10
#define BBL_EMESH_CONFIG__ALL_R 0
#define BBL_EMESH_CONFIG_DATAMASK 0x000007ff
#define BBL_EMESH_CONFIG_RESETVALUE 0x0
#define BBL_EMESH_CONFIG_1 0x00000048
#define BBL_EMESH_CONFIG_1_BASE 0x048
#define BBL_EMESH_CONFIG_1__emesh_filter1_L 25
#define BBL_EMESH_CONFIG_1__emesh_filter1_R 18
#define BBL_EMESH_CONFIG_1__emesh_filter1_WIDTH 8
#define BBL_EMESH_CONFIG_1__emesh_filter1_RESETVALUE 0x00
#define BBL_EMESH_CONFIG_1__emesh_filter0_L 17
#define BBL_EMESH_CONFIG_1__emesh_filter0_R 10
#define BBL_EMESH_CONFIG_1__emesh_filter0_WIDTH 8
#define BBL_EMESH_CONFIG_1__emesh_filter0_RESETVALUE 0x00
#define BBL_EMESH_CONFIG_1__emesh_fil_sel_L 9
#define BBL_EMESH_CONFIG_1__emesh_fil_sel_R 2
#define BBL_EMESH_CONFIG_1__emesh_fil_sel_WIDTH 8
#define BBL_EMESH_CONFIG_1__emesh_fil_sel_RESETVALUE 0x00
#define BBL_EMESH_CONFIG_1__Disable_emesh_filter_L 1
#define BBL_EMESH_CONFIG_1__Disable_emesh_filter_R 1
#define BBL_EMESH_CONFIG_1__Disable_emesh_filter 1
#define BBL_EMESH_CONFIG_1__Disable_emesh_filter_WIDTH 1
#define BBL_EMESH_CONFIG_1__Disable_emesh_filter_RESETVALUE 0x0
#define BBL_EMESH_CONFIG_1__en_bblclk_o0_L 0
#define BBL_EMESH_CONFIG_1__en_bblclk_o0_R 0
#define BBL_EMESH_CONFIG_1__en_bblclk_o0 0
#define BBL_EMESH_CONFIG_1__en_bblclk_o0_WIDTH 1
#define BBL_EMESH_CONFIG_1__en_bblclk_o0_RESETVALUE 0x0
#define BBL_EMESH_CONFIG_1__RESERVED_L 31
#define BBL_EMESH_CONFIG_1__RESERVED_R 26
#define BBL_EMESH_CONFIG_1_WIDTH 26
#define BBL_EMESH_CONFIG_1__WIDTH 26
#define BBL_EMESH_CONFIG_1_ALL_L 25
#define BBL_EMESH_CONFIG_1_ALL_R 0
#define BBL_EMESH_CONFIG_1__ALL_L 25
#define BBL_EMESH_CONFIG_1__ALL_R 0
#define BBL_EMESH_CONFIG_1_DATAMASK 0x03ffffff
#define BBL_EMESH_CONFIG_1_RESETVALUE 0x0
#define BBL_MESH_CONFIG 0x0000004c
#define BBL_MESH_CONFIG_BASE 0x04c
#define BBL_MESH_CONFIG__lfsr_avd_stuck_L 6
#define BBL_MESH_CONFIG__lfsr_avd_stuck_R 6
#define BBL_MESH_CONFIG__lfsr_avd_stuck 6
#define BBL_MESH_CONFIG__lfsr_avd_stuck_WIDTH 1
#define BBL_MESH_CONFIG__lfsr_avd_stuck_RESETVALUE 0x0
#define BBL_MESH_CONFIG__mesh_mfm_en_L 5
#define BBL_MESH_CONFIG__mesh_mfm_en_R 5
#define BBL_MESH_CONFIG__mesh_mfm_en 5
#define BBL_MESH_CONFIG__mesh_mfm_en_WIDTH 1
#define BBL_MESH_CONFIG__mesh_mfm_en_RESETVALUE 0x0
#define BBL_MESH_CONFIG__en_mesh_dyn_L 4
#define BBL_MESH_CONFIG__en_mesh_dyn_R 4
#define BBL_MESH_CONFIG__en_mesh_dyn 4
#define BBL_MESH_CONFIG__en_mesh_dyn_WIDTH 1
#define BBL_MESH_CONFIG__en_mesh_dyn_RESETVALUE 0x0
#define BBL_MESH_CONFIG__en_intmesh_fc_L 3
#define BBL_MESH_CONFIG__en_intmesh_fc_R 3
#define BBL_MESH_CONFIG__en_intmesh_fc 3
#define BBL_MESH_CONFIG__en_intmesh_fc_WIDTH 1
#define BBL_MESH_CONFIG__en_intmesh_fc_RESETVALUE 0x0
#define BBL_MESH_CONFIG__lfsr_period_L 2
#define BBL_MESH_CONFIG__lfsr_period_R 0
#define BBL_MESH_CONFIG__lfsr_period_WIDTH 3
#define BBL_MESH_CONFIG__lfsr_period_RESETVALUE 0x0
#define BBL_MESH_CONFIG__RESERVED_L 31
#define BBL_MESH_CONFIG__RESERVED_R 7
#define BBL_MESH_CONFIG_WIDTH 7
#define BBL_MESH_CONFIG__WIDTH 7
#define BBL_MESH_CONFIG_ALL_L 6
#define BBL_MESH_CONFIG_ALL_R 0
#define BBL_MESH_CONFIG__ALL_L 6
#define BBL_MESH_CONFIG__ALL_R 0
#define BBL_MESH_CONFIG_DATAMASK 0x0000007f
#define BBL_MESH_CONFIG_RESETVALUE 0x0
#define BBL_LFSR_SEED 0x00000050
#define BBL_LFSR_SEED_BASE 0x050
#define BBL_LFSR_SEED__lfsr_seed_L 31
#define BBL_LFSR_SEED__lfsr_seed_R 0
#define BBL_LFSR_SEED__lfsr_seed_WIDTH 32
#define BBL_LFSR_SEED__lfsr_seed_RESETVALUE 0x00000001
#define BBL_LFSR_SEED_WIDTH 32
#define BBL_LFSR_SEED__WIDTH 32
#define BBL_LFSR_SEED_ALL_L 31
#define BBL_LFSR_SEED_ALL_R 0
#define BBL_LFSR_SEED__ALL_L 31
#define BBL_LFSR_SEED__ALL_R 0
#define BBL_LFSR_SEED_DATAMASK 0xffffffff
#define BBL_LFSR_SEED_RESETVALUE 0x1
#define BBL_INPUT_STATUS 0x00000054
#define BBL_INPUT_STATUS_BASE 0x054
#define BBL_INPUT_STATUS__BBL_Input_Pin_Sts_L 17
#define BBL_INPUT_STATUS__BBL_Input_Pin_Sts_R 0
#define BBL_INPUT_STATUS__BBL_Input_Pin_Sts_WIDTH 18
#define BBL_INPUT_STATUS__BBL_Input_Pin_Sts_RESETVALUE 0x0
#define BBL_INPUT_STATUS__RESERVED_L 31
#define BBL_INPUT_STATUS__RESERVED_R 18
#define BBL_INPUT_STATUS_WIDTH 18
#define BBL_INPUT_STATUS__WIDTH 18
#define BBL_INPUT_STATUS_ALL_L 17
#define BBL_INPUT_STATUS_ALL_R 0
#define BBL_INPUT_STATUS__ALL_L 17
#define BBL_INPUT_STATUS__ALL_R 0
#define BBL_INPUT_STATUS_DATAMASK 0x0003ffff
#define BBL_INPUT_STATUS_RESETVALUE 0x0
#define BBL_CONFIG 0x00000058
#define BBL_CONFIG_BASE 0x058
#define BBL_CONFIG__ecc_en_L 14
#define BBL_CONFIG__ecc_en_R 14
#define BBL_CONFIG__ecc_en 14
#define BBL_CONFIG__ecc_en_WIDTH 1
#define BBL_CONFIG__ecc_en_RESETVALUE 0x0
#define BBL_CONFIG__bitflip_cmd_L 13
#define BBL_CONFIG__bitflip_cmd_R 13
#define BBL_CONFIG__bitflip_cmd 13
#define BBL_CONFIG__bitflip_cmd_WIDTH 1
#define BBL_CONFIG__bitflip_cmd_RESETVALUE 0x0
#define BBL_CONFIG__bitflip_period_L 12
#define BBL_CONFIG__bitflip_period_R 11
#define BBL_CONFIG__bitflip_period_WIDTH 2
#define BBL_CONFIG__bitflip_period_RESETVALUE 0x0
#define BBL_CONFIG__sec1280_rawdata_L 10
#define BBL_CONFIG__sec1280_rawdata_R 10
#define BBL_CONFIG__sec1280_rawdata 10
#define BBL_CONFIG__sec1280_rawdata_WIDTH 1
#define BBL_CONFIG__sec1280_rawdata_RESETVALUE 0x0
#define BBL_CONFIG__ckgate_override_L 4
#define BBL_CONFIG__ckgate_override_R 4
#define BBL_CONFIG__ckgate_override 4
#define BBL_CONFIG__ckgate_override_WIDTH 1
#define BBL_CONFIG__ckgate_override_RESETVALUE 0x0
#define BBL_CONFIG__bitflip_en_L 3
#define BBL_CONFIG__bitflip_en_R 3
#define BBL_CONFIG__bitflip_en 3
#define BBL_CONFIG__bitflip_en_WIDTH 1
#define BBL_CONFIG__bitflip_en_RESETVALUE 0x0
#define BBL_CONFIG__bbl_alarm_pol_L 2
#define BBL_CONFIG__bbl_alarm_pol_R 2
#define BBL_CONFIG__bbl_alarm_pol 2
#define BBL_CONFIG__bbl_alarm_pol_WIDTH 1
#define BBL_CONFIG__bbl_alarm_pol_RESETVALUE 0x0
#define BBL_CONFIG__bbl_alarm_mask_L 1
#define BBL_CONFIG__bbl_alarm_mask_R 1
#define BBL_CONFIG__bbl_alarm_mask 1
#define BBL_CONFIG__bbl_alarm_mask_WIDTH 1
#define BBL_CONFIG__bbl_alarm_mask_RESETVALUE 0x0
#define BBL_CONFIG__bbl_alarm_cmos_L 0
#define BBL_CONFIG__bbl_alarm_cmos_R 0
#define BBL_CONFIG__bbl_alarm_cmos 0
#define BBL_CONFIG__bbl_alarm_cmos_WIDTH 1
#define BBL_CONFIG__bbl_alarm_cmos_RESETVALUE 0x0
#define BBL_CONFIG__RESERVED_L 31
#define BBL_CONFIG__RESERVED_R 15
#define BBL_CONFIG_WIDTH 15
#define BBL_CONFIG__WIDTH 15
#define BBL_CONFIG_ALL_L 14
#define BBL_CONFIG_ALL_R 0
#define BBL_CONFIG__ALL_L 14
#define BBL_CONFIG__ALL_R 0
#define BBL_CONFIG_DATAMASK 0x00007c1f
#define BBL_CONFIG_RESETVALUE 0x0
#define BBL_CONFIG_1 0x0000005c
#define BBL_CONFIG_1_BASE 0x05c
#define BBL_CONFIG_1__dly_src_sel_L 7
#define BBL_CONFIG_1__dly_src_sel_R 6
#define BBL_CONFIG_1__dly_src_sel_WIDTH 2
#define BBL_CONFIG_1__dly_src_sel_RESETVALUE 0x0
#define BBL_CONFIG_1__l1_rst_mask_L 5
#define BBL_CONFIG_1__l1_rst_mask_R 5
#define BBL_CONFIG_1__l1_rst_mask 5
#define BBL_CONFIG_1__l1_rst_mask_WIDTH 1
#define BBL_CONFIG_1__l1_rst_mask_RESETVALUE 0x1
#define BBL_CONFIG_1__test_isolate_L 4
#define BBL_CONFIG_1__test_isolate_R 4
#define BBL_CONFIG_1__test_isolate 4
#define BBL_CONFIG_1__test_isolate_WIDTH 1
#define BBL_CONFIG_1__test_isolate_RESETVALUE 0x0
#define BBL_CONFIG_1__test_clear_L 3
#define BBL_CONFIG_1__test_clear_R 3
#define BBL_CONFIG_1__test_clear 3
#define BBL_CONFIG_1__test_clear_WIDTH 1
#define BBL_CONFIG_1__test_clear_RESETVALUE 0x0
#define BBL_CONFIG_1__reg_clk_en_L 2
#define BBL_CONFIG_1__reg_clk_en_R 2
#define BBL_CONFIG_1__reg_clk_en 2
#define BBL_CONFIG_1__reg_clk_en_WIDTH 1
#define BBL_CONFIG_1__reg_clk_en_RESETVALUE 0x1
#define BBL_CONFIG_1__sec1280_clr_L 1
#define BBL_CONFIG_1__sec1280_clr_R 1
#define BBL_CONFIG_1__sec1280_clr 1
#define BBL_CONFIG_1__sec1280_clr_WIDTH 1
#define BBL_CONFIG_1__sec1280_clr_RESETVALUE 0x0
#define BBL_CONFIG_1__soft_rst_L 0
#define BBL_CONFIG_1__soft_rst_R 0
#define BBL_CONFIG_1__soft_rst 0
#define BBL_CONFIG_1__soft_rst_WIDTH 1
#define BBL_CONFIG_1__soft_rst_RESETVALUE 0x0
#define BBL_CONFIG_1__RESERVED_L 31
#define BBL_CONFIG_1__RESERVED_R 8
#define BBL_CONFIG_1_WIDTH 8
#define BBL_CONFIG_1__WIDTH 8
#define BBL_CONFIG_1_ALL_L 7
#define BBL_CONFIG_1_ALL_R 0
#define BBL_CONFIG_1__ALL_L 7
#define BBL_CONFIG_1__ALL_R 0
#define BBL_CONFIG_1_DATAMASK 0x000000ff
#define BBL_CONFIG_1_RESETVALUE 0x24
#define BBL_TMON_CONFIG 0x00000060
#define BBL_TMON_CONFIG_BASE 0x060
#define BBL_TMON_CONFIG__min_lim_L 30
#define BBL_TMON_CONFIG__min_lim_R 21
#define BBL_TMON_CONFIG__min_lim_WIDTH 10
#define BBL_TMON_CONFIG__min_lim_RESETVALUE 0x3a9
#define BBL_TMON_CONFIG__max_lim_L 20
#define BBL_TMON_CONFIG__max_lim_R 11
#define BBL_TMON_CONFIG__max_lim_WIDTH 10
#define BBL_TMON_CONFIG__max_lim_RESETVALUE 0x253
#define BBL_TMON_CONFIG__delta_lim_L 10
#define BBL_TMON_CONFIG__delta_lim_R 1
#define BBL_TMON_CONFIG__delta_lim_WIDTH 10
#define BBL_TMON_CONFIG__delta_lim_RESETVALUE 0x14
#define BBL_TMON_CONFIG__temp_pwrdn_L 0
#define BBL_TMON_CONFIG__temp_pwrdn_R 0
#define BBL_TMON_CONFIG__temp_pwrdn 0
#define BBL_TMON_CONFIG__temp_pwrdn_WIDTH 1
#define BBL_TMON_CONFIG__temp_pwrdn_RESETVALUE 0x1
#define BBL_TMON_CONFIG__RESERVED 31
#define BBL_TMON_CONFIG_WIDTH 31
#define BBL_TMON_CONFIG__WIDTH 31
#define BBL_TMON_CONFIG_ALL_L 30
#define BBL_TMON_CONFIG_ALL_R 0
#define BBL_TMON_CONFIG__ALL_L 30
#define BBL_TMON_CONFIG__ALL_R 0
#define BBL_TMON_CONFIG_DATAMASK 0x7fffffff
#define BBL_TMON_CONFIG_RESETVALUE 0x75329829
#define BBL_TMON_CONFIG_1 0x00000064
#define BBL_TMON_CONFIG_1_BASE 0x064
#define BBL_TMON_CONFIG_1__tmon_ate_done_L 9
#define BBL_TMON_CONFIG_1__tmon_ate_done_R 9
#define BBL_TMON_CONFIG_1__tmon_ate_done 9
#define BBL_TMON_CONFIG_1__tmon_ate_done_WIDTH 1
#define BBL_TMON_CONFIG_1__tmon_ate_done_RESETVALUE 0x0
#define BBL_TMON_CONFIG_1__tmon_ate_pul_L 8
#define BBL_TMON_CONFIG_1__tmon_ate_pul_R 8
#define BBL_TMON_CONFIG_1__tmon_ate_pul 8
#define BBL_TMON_CONFIG_1__tmon_ate_pul_WIDTH 1
#define BBL_TMON_CONFIG_1__tmon_ate_pul_RESETVALUE 0x0
#define BBL_TMON_CONFIG_1__tmon_ate_en_L 7
#define BBL_TMON_CONFIG_1__tmon_ate_en_R 7
#define BBL_TMON_CONFIG_1__tmon_ate_en 7
#define BBL_TMON_CONFIG_1__tmon_ate_en_WIDTH 1
#define BBL_TMON_CONFIG_1__tmon_ate_en_RESETVALUE 0x0
#define BBL_TMON_CONFIG_1__tmon_samp_L 6
#define BBL_TMON_CONFIG_1__tmon_samp_R 2
#define BBL_TMON_CONFIG_1__tmon_samp_WIDTH 5
#define BBL_TMON_CONFIG_1__tmon_samp_RESETVALUE 0x8
#define BBL_TMON_CONFIG_1__temp_sample_rate_L 1
#define BBL_TMON_CONFIG_1__temp_sample_rate_R 0
#define BBL_TMON_CONFIG_1__temp_sample_rate_WIDTH 2
#define BBL_TMON_CONFIG_1__temp_sample_rate_RESETVALUE 0x0
#define BBL_TMON_CONFIG_1__RESERVED_L 31
#define BBL_TMON_CONFIG_1__RESERVED_R 10
#define BBL_TMON_CONFIG_1_WIDTH 10
#define BBL_TMON_CONFIG_1__WIDTH 10
#define BBL_TMON_CONFIG_1_ALL_L 9
#define BBL_TMON_CONFIG_1_ALL_R 0
#define BBL_TMON_CONFIG_1__ALL_L 9
#define BBL_TMON_CONFIG_1__ALL_R 0
#define BBL_TMON_CONFIG_1_DATAMASK 0x000003ff
#define BBL_TMON_CONFIG_1_RESETVALUE 0x20
#define BBL_STAT 0x00000068
#define BBL_STAT_BASE 0x068
#define BBL_STAT__emesh_tamper_status_nonsticky_L 30
#define BBL_STAT__emesh_tamper_status_nonsticky_R 13
#define BBL_STAT__emesh_tamper_status_nonsticky_WIDTH 18
#define BBL_STAT__emesh_tamper_status_nonsticky_RESETVALUE 0x0
#define BBL_STAT__rsvd_io_L 12
#define BBL_STAT__rsvd_io_R 12
#define BBL_STAT__rsvd_io 12
#define BBL_STAT__rsvd_io_WIDTH 1
#define BBL_STAT__rsvd_io_RESETVALUE 0x0
#define BBL_STAT__dft_iso_dis_L 11
#define BBL_STAT__dft_iso_dis_R 11
#define BBL_STAT__dft_iso_dis 11
#define BBL_STAT__dft_iso_dis_WIDTH 1
#define BBL_STAT__dft_iso_dis_RESETVALUE 0x0
#define BBL_STAT__iso_vdd_L 10
#define BBL_STAT__iso_vdd_R 10
#define BBL_STAT__iso_vdd 10
#define BBL_STAT__iso_vdd_WIDTH 1
#define BBL_STAT__iso_vdd_RESETVALUE 0x1
#define BBL_STAT__adc_val_L 9
#define BBL_STAT__adc_val_R 0
#define BBL_STAT__adc_val_WIDTH 10
#define BBL_STAT__adc_val_RESETVALUE 0x0
#define BBL_STAT__RESERVED 31
#define BBL_STAT_WIDTH 31
#define BBL_STAT__WIDTH 31
#define BBL_STAT_ALL_L 30
#define BBL_STAT_ALL_R 0
#define BBL_STAT__ALL_L 30
#define BBL_STAT__ALL_R 0
#define BBL_STAT_DATAMASK 0x7fffffff
#define BBL_STAT_RESETVALUE 0x400
#define PAD_DRIVE_SEL_CFG 0x0000006c
#define PAD_DRIVE_SEL_CFG_BASE 0x06c
#define PAD_DRIVE_SEL_CFG__emesh_L 11
#define PAD_DRIVE_SEL_CFG__emesh_R 0
#define PAD_DRIVE_SEL_CFG__emesh_WIDTH 12
#define PAD_DRIVE_SEL_CFG__emesh_RESETVALUE 0x000
#define PAD_DRIVE_SEL_CFG__RESERVED_L 31
#define PAD_DRIVE_SEL_CFG__RESERVED_R 12
#define PAD_DRIVE_SEL_CFG_WIDTH 12
#define PAD_DRIVE_SEL_CFG__WIDTH 12
#define PAD_DRIVE_SEL_CFG_ALL_L 11
#define PAD_DRIVE_SEL_CFG_ALL_R 0
#define PAD_DRIVE_SEL_CFG__ALL_L 11
#define PAD_DRIVE_SEL_CFG__ALL_R 0
#define PAD_DRIVE_SEL_CFG_DATAMASK 0x00000fff
#define PAD_DRIVE_SEL_CFG_RESETVALUE 0x0
#define PAD_SRC_CFG 0x00000070
#define PAD_SRC_CFG_BASE 0x070
#define PAD_SRC_CFG__bbl_clk_on_alarm_out_L 7
#define PAD_SRC_CFG__bbl_clk_on_alarm_out_R 7
#define PAD_SRC_CFG__bbl_clk_on_alarm_out 7
#define PAD_SRC_CFG__bbl_clk_on_alarm_out_WIDTH 1
#define PAD_SRC_CFG__bbl_clk_on_alarm_out_RESETVALUE 0x1
#define PAD_SRC_CFG__sticky_emesh_tamper_L 6
#define PAD_SRC_CFG__sticky_emesh_tamper_R 6
#define PAD_SRC_CFG__sticky_emesh_tamper 6
#define PAD_SRC_CFG__sticky_emesh_tamper_WIDTH 1
#define PAD_SRC_CFG__sticky_emesh_tamper_RESETVALUE 0x1
#define PAD_SRC_CFG__tamper_out_L 5
#define PAD_SRC_CFG__tamper_out_R 5
#define PAD_SRC_CFG__tamper_out 5
#define PAD_SRC_CFG__tamper_out_WIDTH 1
#define PAD_SRC_CFG__tamper_out_RESETVALUE 0x1
#define PAD_SRC_CFG__alarm_L 4
#define PAD_SRC_CFG__alarm_R 4
#define PAD_SRC_CFG__alarm 4
#define PAD_SRC_CFG__alarm_WIDTH 1
#define PAD_SRC_CFG__alarm_RESETVALUE 0x1
#define PAD_SRC_CFG__emesh_L 3
#define PAD_SRC_CFG__emesh_R 0
#define PAD_SRC_CFG__emesh_WIDTH 4
#define PAD_SRC_CFG__emesh_RESETVALUE 0xf
#define PAD_SRC_CFG__RESERVED_L 31
#define PAD_SRC_CFG__RESERVED_R 8
#define PAD_SRC_CFG_WIDTH 8
#define PAD_SRC_CFG__WIDTH 8
#define PAD_SRC_CFG_ALL_L 7
#define PAD_SRC_CFG_ALL_R 0
#define PAD_SRC_CFG__ALL_L 7
#define PAD_SRC_CFG__ALL_R 0
#define PAD_SRC_CFG_DATAMASK 0x000000ff
#define PAD_SRC_CFG_RESETVALUE 0xff
#define PAD_HYS_EN_CFG 0x00000074
#define PAD_HYS_EN_CFG_BASE 0x074
#define PAD_HYS_EN_CFG__tamper_io_L 9
#define PAD_HYS_EN_CFG__tamper_io_R 0
#define PAD_HYS_EN_CFG__tamper_io_WIDTH 10
#define PAD_HYS_EN_CFG__tamper_io_RESETVALUE 0x0
#define PAD_HYS_EN_CFG__RESERVED_L 31
#define PAD_HYS_EN_CFG__RESERVED_R 10
#define PAD_HYS_EN_CFG_WIDTH 10
#define PAD_HYS_EN_CFG__WIDTH 10
#define PAD_HYS_EN_CFG_ALL_L 9
#define PAD_HYS_EN_CFG_ALL_R 0
#define PAD_HYS_EN_CFG__ALL_L 9
#define PAD_HYS_EN_CFG__ALL_R 0
#define PAD_HYS_EN_CFG_DATAMASK 0x000003ff
#define PAD_HYS_EN_CFG_RESETVALUE 0x0
#define PAD_PULL_DN_CFG 0x00000078
#define PAD_PULL_DN_CFG_BASE 0x078
#define PAD_PULL_DN_CFG__alarm_L 13
#define PAD_PULL_DN_CFG__alarm_R 13
#define PAD_PULL_DN_CFG__alarm 13
#define PAD_PULL_DN_CFG__alarm_WIDTH 1
#define PAD_PULL_DN_CFG__alarm_RESETVALUE 0x0
#define PAD_PULL_DN_CFG__tamper_out_L 12
#define PAD_PULL_DN_CFG__tamper_out_R 12
#define PAD_PULL_DN_CFG__tamper_out 12
#define PAD_PULL_DN_CFG__tamper_out_WIDTH 1
#define PAD_PULL_DN_CFG__tamper_out_RESETVALUE 0x0
#define PAD_PULL_DN_CFG__ext_pmusel_L 11
#define PAD_PULL_DN_CFG__ext_pmusel_R 11
#define PAD_PULL_DN_CFG__ext_pmusel 11
#define PAD_PULL_DN_CFG__ext_pmusel_WIDTH 1
#define PAD_PULL_DN_CFG__ext_pmusel_RESETVALUE 0x1
#define PAD_PULL_DN_CFG__ext_wakeup_L 10
#define PAD_PULL_DN_CFG__ext_wakeup_R 10
#define PAD_PULL_DN_CFG__ext_wakeup 10
#define PAD_PULL_DN_CFG__ext_wakeup_WIDTH 1
#define PAD_PULL_DN_CFG__ext_wakeup_RESETVALUE 0x1
#define PAD_PULL_DN_CFG__tamper_io_L 9
#define PAD_PULL_DN_CFG__tamper_io_R 0
#define PAD_PULL_DN_CFG__tamper_io_WIDTH 10
#define PAD_PULL_DN_CFG__tamper_io_RESETVALUE 0x3ff
#define PAD_PULL_DN_CFG__RESERVED_L 31
#define PAD_PULL_DN_CFG__RESERVED_R 14
#define PAD_PULL_DN_CFG_WIDTH 14
#define PAD_PULL_DN_CFG__WIDTH 14
#define PAD_PULL_DN_CFG_ALL_L 13
#define PAD_PULL_DN_CFG_ALL_R 0
#define PAD_PULL_DN_CFG__ALL_L 13
#define PAD_PULL_DN_CFG__ALL_R 0
#define PAD_PULL_DN_CFG_DATAMASK 0x00003fff
#define PAD_PULL_DN_CFG_RESETVALUE 0xfff
#define DBG_CONFIG 0x0000007c
#define DBG_CONFIG_BASE 0x07c
#define DBG_CONFIG__tamper_immesh_p0_L 0
#define DBG_CONFIG__tamper_immesh_p0_R 0
#define DBG_CONFIG__tamper_immesh_p0 0
#define DBG_CONFIG__tamper_immesh_p0_WIDTH 1
#define DBG_CONFIG__tamper_immesh_p0_RESETVALUE 0x0
#define DBG_CONFIG__RESERVED_L 31
#define DBG_CONFIG__RESERVED_R 1
#define DBG_CONFIG_WIDTH 1
#define DBG_CONFIG__WIDTH 1
#define DBG_CONFIG_ALL_L 0
#define DBG_CONFIG_ALL_R 0
#define DBG_CONFIG__ALL_L 0
#define DBG_CONFIG__ALL_R 0
#define DBG_CONFIG_DATAMASK 0x00000001
#define DBG_CONFIG_RESETVALUE 0x0
#define TAMPER_INP_TIMEBASE 0x00000080
#define TAMPER_INP_TIMEBASE_BASE 0x080
#define TAMPER_INP_TIMEBASE__tamper_inp_timebase0_L 7
#define TAMPER_INP_TIMEBASE__tamper_inp_timebase0_R 0
#define TAMPER_INP_TIMEBASE__tamper_inp_timebase0_WIDTH 8
#define TAMPER_INP_TIMEBASE__tamper_inp_timebase0_RESETVALUE 0x00
#define TAMPER_INP_TIMEBASE__RESERVED_L 31
#define TAMPER_INP_TIMEBASE__RESERVED_R 8
#define TAMPER_INP_TIMEBASE_WIDTH 8
#define TAMPER_INP_TIMEBASE__WIDTH 8
#define TAMPER_INP_TIMEBASE_ALL_L 7
#define TAMPER_INP_TIMEBASE_ALL_R 0
#define TAMPER_INP_TIMEBASE__ALL_L 7
#define TAMPER_INP_TIMEBASE__ALL_R 0
#define TAMPER_INP_TIMEBASE_DATAMASK 0x000000ff
#define TAMPER_INP_TIMEBASE_RESETVALUE 0x0
#define FILTER_THREHOLD_CONFIG1 0x00000084
#define FILTER_THREHOLD_CONFIG1_BASE 0x084
#define FILTER_THREHOLD_CONFIG1__emsh_open_fil_thres_L 23
#define FILTER_THREHOLD_CONFIG1__emsh_open_fil_thres_R 16
#define FILTER_THREHOLD_CONFIG1__emsh_open_fil_thres_WIDTH 8
#define FILTER_THREHOLD_CONFIG1__emsh_open_fil_thres_RESETVALUE 0x01
#define FILTER_THREHOLD_CONFIG1__emsh_fil_thres_L 15
#define FILTER_THREHOLD_CONFIG1__emsh_fil_thres_R 8
#define FILTER_THREHOLD_CONFIG1__emsh_fil_thres_WIDTH 8
#define FILTER_THREHOLD_CONFIG1__emsh_fil_thres_RESETVALUE 0x01
#define FILTER_THREHOLD_CONFIG1__imesh_fil_thres_L 7
#define FILTER_THREHOLD_CONFIG1__imesh_fil_thres_R 0
#define FILTER_THREHOLD_CONFIG1__imesh_fil_thres_WIDTH 8
#define FILTER_THREHOLD_CONFIG1__imesh_fil_thres_RESETVALUE 0x01
#define FILTER_THREHOLD_CONFIG1__RESERVED_L 31
#define FILTER_THREHOLD_CONFIG1__RESERVED_R 24
#define FILTER_THREHOLD_CONFIG1_WIDTH 24
#define FILTER_THREHOLD_CONFIG1__WIDTH 24
#define FILTER_THREHOLD_CONFIG1_ALL_L 23
#define FILTER_THREHOLD_CONFIG1_ALL_R 0
#define FILTER_THREHOLD_CONFIG1__ALL_L 23
#define FILTER_THREHOLD_CONFIG1__ALL_R 0
#define FILTER_THREHOLD_CONFIG1_DATAMASK 0x00ffffff
#define FILTER_THREHOLD_CONFIG1_RESETVALUE 0x10101
#define FILTER_THREHOLD_CONFIG2 0x00000088
#define FILTER_THREHOLD_CONFIG2_BASE 0x088
#define FILTER_THREHOLD_CONFIG2__deglitch_fil_cnt_thres_L 2
#define FILTER_THREHOLD_CONFIG2__deglitch_fil_cnt_thres_R 0
#define FILTER_THREHOLD_CONFIG2__deglitch_fil_cnt_thres_WIDTH 3
#define FILTER_THREHOLD_CONFIG2__deglitch_fil_cnt_thres_RESETVALUE 0x1
#define FILTER_THREHOLD_CONFIG2__RESERVED_L 31
#define FILTER_THREHOLD_CONFIG2__RESERVED_R 3
#define FILTER_THREHOLD_CONFIG2_WIDTH 3
#define FILTER_THREHOLD_CONFIG2__WIDTH 3
#define FILTER_THREHOLD_CONFIG2_ALL_L 2
#define FILTER_THREHOLD_CONFIG2_ALL_R 0
#define FILTER_THREHOLD_CONFIG2__ALL_L 2
#define FILTER_THREHOLD_CONFIG2__ALL_R 0
#define FILTER_THREHOLD_CONFIG2_DATAMASK 0x00000007
#define FILTER_THREHOLD_CONFIG2_RESETVALUE 0x1
#define BBL_RSVD 0x0000008c
#define BBL_RSVD_BASE 0x08c
#define BBL_RSVD__Sticky_First_Tamper_Source_L 20
#define BBL_RSVD__Sticky_First_Tamper_Source_R 8
#define BBL_RSVD__Sticky_First_Tamper_Source_WIDTH 13
#define BBL_RSVD__Sticky_First_Tamper_Source_RESETVALUE 0x0
#define BBL_RSVD__rsvd_L 7
#define BBL_RSVD__rsvd_R 0
#define BBL_RSVD__rsvd_WIDTH 8
#define BBL_RSVD__rsvd_RESETVALUE 0x00
#define BBL_RSVD__RESERVED_L 31
#define BBL_RSVD__RESERVED_R 21
#define BBL_RSVD_WIDTH 21
#define BBL_RSVD__WIDTH 21
#define BBL_RSVD_ALL_L 20
#define BBL_RSVD_ALL_R 0
#define BBL_RSVD__ALL_L 20
#define BBL_RSVD__ALL_R 0
#define BBL_RSVD_DATAMASK 0x001fffff
#define BBL_RSVD_RESETVALUE 0x0
#define BBL_MACRO_CFG 0x00000090
#define BBL_MACRO_CFG_BASE 0x090
#define BBL_MACRO_CFG__fmon_violation_counter_threshold_L 31
#define BBL_MACRO_CFG__fmon_violation_counter_threshold_R 26
#define BBL_MACRO_CFG__fmon_violation_counter_threshold_WIDTH 6
#define BBL_MACRO_CFG__fmon_violation_counter_threshold_RESETVALUE 0x0
#define BBL_MACRO_CFG__alarm_pad_sel_L 25
#define BBL_MACRO_CFG__alarm_pad_sel_R 24
#define BBL_MACRO_CFG__alarm_pad_sel_WIDTH 2
#define BBL_MACRO_CFG__alarm_pad_sel_RESETVALUE 0x0
#define BBL_MACRO_CFG__lfo_ate_en_L 23
#define BBL_MACRO_CFG__lfo_ate_en_R 23
#define BBL_MACRO_CFG__lfo_ate_en 23
#define BBL_MACRO_CFG__lfo_ate_en_WIDTH 1
#define BBL_MACRO_CFG__lfo_ate_en_RESETVALUE 0x0
#define BBL_MACRO_CFG__xtal_ictl_L 22
#define BBL_MACRO_CFG__xtal_ictl_R 22
#define BBL_MACRO_CFG__xtal_ictl 22
#define BBL_MACRO_CFG__xtal_ictl_WIDTH 1
#define BBL_MACRO_CFG__xtal_ictl_RESETVALUE 0x0
#define BBL_MACRO_CFG__fmon_trim_L 21
#define BBL_MACRO_CFG__fmon_trim_R 18
#define BBL_MACRO_CFG__fmon_trim_WIDTH 4
#define BBL_MACRO_CFG__fmon_trim_RESETVALUE 0x6
#define BBL_MACRO_CFG__fmon_rstb_L 17
#define BBL_MACRO_CFG__fmon_rstb_R 17
#define BBL_MACRO_CFG__fmon_rstb 17
#define BBL_MACRO_CFG__fmon_rstb_WIDTH 1
#define BBL_MACRO_CFG__fmon_rstb_RESETVALUE 0x0
#define BBL_MACRO_CFG__fmon_pd_L 16
#define BBL_MACRO_CFG__fmon_pd_R 16
#define BBL_MACRO_CFG__fmon_pd 16
#define BBL_MACRO_CFG__fmon_pd_WIDTH 1
#define BBL_MACRO_CFG__fmon_pd_RESETVALUE 0x1
#define BBL_MACRO_CFG__bg_pd_L 15
#define BBL_MACRO_CFG__bg_pd_R 15
#define BBL_MACRO_CFG__bg_pd 15
#define BBL_MACRO_CFG__bg_pd_WIDTH 1
#define BBL_MACRO_CFG__bg_pd_RESETVALUE 0x1
#define BBL_MACRO_CFG__vmon_cmp_t_sel_L 14
#define BBL_MACRO_CFG__vmon_cmp_t_sel_R 13
#define BBL_MACRO_CFG__vmon_cmp_t_sel_WIDTH 2
#define BBL_MACRO_CFG__vmon_cmp_t_sel_RESETVALUE 0x1
#define BBL_MACRO_CFG__vmon_cmp_b_sel_L 12
#define BBL_MACRO_CFG__vmon_cmp_b_sel_R 11
#define BBL_MACRO_CFG__vmon_cmp_b_sel_WIDTH 2
#define BBL_MACRO_CFG__vmon_cmp_b_sel_RESETVALUE 0x2
#define BBL_MACRO_CFG__vmon_pd_L 10
#define BBL_MACRO_CFG__vmon_pd_R 10
#define BBL_MACRO_CFG__vmon_pd 10
#define BBL_MACRO_CFG__vmon_pd_WIDTH 1
#define BBL_MACRO_CFG__vmon_pd_RESETVALUE 0x1
#define BBL_MACRO_CFG__tmon_test_en_L 9
#define BBL_MACRO_CFG__tmon_test_en_R 9
#define BBL_MACRO_CFG__tmon_test_en 9
#define BBL_MACRO_CFG__tmon_test_en_WIDTH 1
#define BBL_MACRO_CFG__tmon_test_en_RESETVALUE 0x0
#define BBL_MACRO_CFG__tmon_adc_pd_L 8
#define BBL_MACRO_CFG__tmon_adc_pd_R 8
#define BBL_MACRO_CFG__tmon_adc_pd 8
#define BBL_MACRO_CFG__tmon_adc_pd_WIDTH 1
#define BBL_MACRO_CFG__tmon_adc_pd_RESETVALUE 0x1
#define BBL_MACRO_CFG__tmon_rstb_L 7
#define BBL_MACRO_CFG__tmon_rstb_R 7
#define BBL_MACRO_CFG__tmon_rstb 7
#define BBL_MACRO_CFG__tmon_rstb_WIDTH 1
#define BBL_MACRO_CFG__tmon_rstb_RESETVALUE 0x0
#define BBL_MACRO_CFG__tmon_ctrl_L 6
#define BBL_MACRO_CFG__tmon_ctrl_R 0
#define BBL_MACRO_CFG__tmon_ctrl_WIDTH 7
#define BBL_MACRO_CFG__tmon_ctrl_RESETVALUE 0x5
#define BBL_MACRO_CFG_WIDTH 32
#define BBL_MACRO_CFG__WIDTH 32
#define BBL_MACRO_CFG_ALL_L 31
#define BBL_MACRO_CFG_ALL_R 0
#define BBL_MACRO_CFG__ALL_L 31
#define BBL_MACRO_CFG__ALL_R 0
#define BBL_MACRO_CFG_DATAMASK 0xffffffff
#define BBL_MACRO_CFG_RESETVALUE 0x19b505
#define BBL_MACRO_STAT 0x00000094
#define BBL_MACRO_STAT_BASE 0x094
#define BBL_MACRO_STAT__vmon_cmp_t_L 4
#define BBL_MACRO_STAT__vmon_cmp_t_R 4
#define BBL_MACRO_STAT__vmon_cmp_t 4
#define BBL_MACRO_STAT__vmon_cmp_t_WIDTH 1
#define BBL_MACRO_STAT__vmon_cmp_t_RESETVALUE 0x0
#define BBL_MACRO_STAT__vmon_cmp_b_L 3
#define BBL_MACRO_STAT__vmon_cmp_b_R 3
#define BBL_MACRO_STAT__vmon_cmp_b 3
#define BBL_MACRO_STAT__vmon_cmp_b_WIDTH 1
#define BBL_MACRO_STAT__vmon_cmp_b_RESETVALUE 0x0
#define BBL_MACRO_STAT__vmon_cmp_data_L 2
#define BBL_MACRO_STAT__vmon_cmp_data_R 2
#define BBL_MACRO_STAT__vmon_cmp_data 2
#define BBL_MACRO_STAT__vmon_cmp_data_WIDTH 1
#define BBL_MACRO_STAT__vmon_cmp_data_RESETVALUE 0x0
#define BBL_MACRO_STAT__fmon_stat_L 1
#define BBL_MACRO_STAT__fmon_stat_R 0
#define BBL_MACRO_STAT__fmon_stat_WIDTH 2
#define BBL_MACRO_STAT__fmon_stat_RESETVALUE 0x0
#define BBL_MACRO_STAT__RESERVED_L 31
#define BBL_MACRO_STAT__RESERVED_R 5
#define BBL_MACRO_STAT_WIDTH 5
#define BBL_MACRO_STAT__WIDTH 5
#define BBL_MACRO_STAT_ALL_L 4
#define BBL_MACRO_STAT_ALL_R 0
#define BBL_MACRO_STAT__ALL_L 4
#define BBL_MACRO_STAT__ALL_R 0
#define BBL_MACRO_STAT_DATAMASK 0x0000001f
#define BBL_MACRO_STAT_RESETVALUE 0x0
#define BBL_VDS 0x00000098
#define BBL_VDS_BASE 0x098
#define BBL_VDS__reg_pu_L 1
#define BBL_VDS__reg_pu_R 1
#define BBL_VDS__reg_pu 1
#define BBL_VDS__reg_pu_WIDTH 1
#define BBL_VDS__reg_pu_RESETVALUE 0x0
#define BBL_VDS__ldo_pwrdn_L 0
#define BBL_VDS__ldo_pwrdn_R 0
#define BBL_VDS__ldo_pwrdn 0
#define BBL_VDS__ldo_pwrdn_WIDTH 1
#define BBL_VDS__ldo_pwrdn_RESETVALUE 0x0
#define BBL_VDS__RESERVED_L 31
#define BBL_VDS__RESERVED_R 2
#define BBL_VDS_WIDTH 2
#define BBL_VDS__WIDTH 2
#define BBL_VDS_ALL_L 1
#define BBL_VDS_ALL_R 0
#define BBL_VDS__ALL_L 1
#define BBL_VDS__ALL_R 0
#define BBL_VDS_DATAMASK 0x00000003
#define BBL_VDS_RESETVALUE 0x0
#define BBL_WR_BLOCK 0x000001cc
#define BBL_WR_BLOCK_BASE 0x1cc
#define BBL_WR_BLOCK__reg_wr_blk_L 1
#define BBL_WR_BLOCK__reg_wr_blk_R 1
#define BBL_WR_BLOCK__reg_wr_blk 1
#define BBL_WR_BLOCK__reg_wr_blk_WIDTH 1
#define BBL_WR_BLOCK__reg_wr_blk_RESETVALUE 0x0
#define BBL_WR_BLOCK__bbram_wr_blk_L 0
#define BBL_WR_BLOCK__bbram_wr_blk_R 0
#define BBL_WR_BLOCK__bbram_wr_blk 0
#define BBL_WR_BLOCK__bbram_wr_blk_WIDTH 1
#define BBL_WR_BLOCK__bbram_wr_blk_RESETVALUE 0x0
#define BBL_WR_BLOCK__RESERVED_L 31
#define BBL_WR_BLOCK__RESERVED_R 2
#define BBL_WR_BLOCK_WIDTH 2
#define BBL_WR_BLOCK__WIDTH 2
#define BBL_WR_BLOCK_ALL_L 1
#define BBL_WR_BLOCK_ALL_R 0
#define BBL_WR_BLOCK__ALL_L 1
#define BBL_WR_BLOCK__ALL_R 0
#define BBL_WR_BLOCK_DATAMASK 0x00000003
#define BBL_WR_BLOCK_RESETVALUE 0x0

#endif /* __BBL_REGS_H__ */
