/******************************************************************************
 *  Copyright (C) 2017 Broadcom. The term "Broadcom" refers to Broadcom Limited
 *  and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the
 *  terms and conditions of a separate, written license agreement executed
 *  between you and Broadcom (an "Authorized License").  Except as set forth in
 *  an Authorized License, Broadcom grants no license (express or implied),
 *  right to use, or waiver of any kind with respect to the Software, and
 *  Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE,
 *  THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 *  IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization,
 *  constitutes the valuable trade secrets of Broadcom, and you shall use all
 *  reasonable efforts to protect the confidentiality thereof, and to use this
 *  information only in connection with your use of Broadcom integrated circuit
 *  products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 *  "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 *  OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 *  RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 *  IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *  PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *  ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE
 *  ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
 *  ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 *  INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 *  RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 *  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 *  EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 *  WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 *  FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/
#ifndef __FT_REGS_H__
#define __FT_REGS_H__

#ifdef __cplusplus
extern "C"
{
#endif

/* TODO: This will eventually come from headers auto-generated from DTS files */

#define FLEX_TIMER_CLK_PRESCALE 0x440c0800
#define FLEX_TIMER_CLK_PRESCALE_BASE 0x800
#define FLEX_TIMER_CLK_PRESCALE_OFFSET 0x440c0800
#define FLEX_TIMER_CLK_PRESCALE__div_L 9
#define FLEX_TIMER_CLK_PRESCALE__div_R 0
#define FLEX_TIMER_CLK_PRESCALE__div_WIDTH 10
#define FLEX_TIMER_CLK_PRESCALE__div_RESETVALUE 0x0
#define FLEX_TIMER_CLK_PRESCALE__RESERVED_L 31
#define FLEX_TIMER_CLK_PRESCALE__RESERVED_R 10
#define FLEX_TIMER_CLK_PRESCALE_WIDTH 10
#define FLEX_TIMER_CLK_PRESCALE__WIDTH 10
#define FLEX_TIMER_CLK_PRESCALE_ALL_L 9
#define FLEX_TIMER_CLK_PRESCALE_ALL_R 0
#define FLEX_TIMER_CLK_PRESCALE__ALL_L 9
#define FLEX_TIMER_CLK_PRESCALE__ALL_R 0
#define FLEX_TIMER_CLK_PRESCALE_DATAMASK 0x000003ff
#define FLEX_TIMER_CLK_PRESCALE_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS 0x440c0804
#define FLEX_TIMER_INTR_STATUS_BASE 0x804
#define FLEX_TIMER_INTR_STATUS_OFFSET 0x440c0804
#define FLEX_TIMER_INTR_STATUS__sos_L 18
#define FLEX_TIMER_INTR_STATUS__sos_R 18
#define FLEX_TIMER_INTR_STATUS__sos 18
#define FLEX_TIMER_INTR_STATUS__sos_WIDTH 1
#define FLEX_TIMER_INTR_STATUS__sos_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__timeout_L 17
#define FLEX_TIMER_INTR_STATUS__timeout_R 17
#define FLEX_TIMER_INTR_STATUS__timeout 17
#define FLEX_TIMER_INTR_STATUS__timeout_WIDTH 1
#define FLEX_TIMER_INTR_STATUS__timeout_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__empty_intr_L 16
#define FLEX_TIMER_INTR_STATUS__empty_intr_R 14
#define FLEX_TIMER_INTR_STATUS__empty_intr_WIDTH 3
#define FLEX_TIMER_INTR_STATUS__empty_intr_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__full_intr_L 13
#define FLEX_TIMER_INTR_STATUS__full_intr_R 11
#define FLEX_TIMER_INTR_STATUS__full_intr_WIDTH 3
#define FLEX_TIMER_INTR_STATUS__full_intr_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__watermakr_intr_L 10
#define FLEX_TIMER_INTR_STATUS__watermakr_intr_R 8
#define FLEX_TIMER_INTR_STATUS__watermakr_intr_WIDTH 3
#define FLEX_TIMER_INTR_STATUS__watermakr_intr_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__overrun_L 7
#define FLEX_TIMER_INTR_STATUS__overrun_R 4
#define FLEX_TIMER_INTR_STATUS__overrun_WIDTH 4
#define FLEX_TIMER_INTR_STATUS__overrun_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__new_ts_intr_L 3
#define FLEX_TIMER_INTR_STATUS__new_ts_intr_R 0
#define FLEX_TIMER_INTR_STATUS__new_ts_intr_WIDTH 4
#define FLEX_TIMER_INTR_STATUS__new_ts_intr_RESETVALUE 0x0
#define FLEX_TIMER_INTR_STATUS__RESERVED_L 31
#define FLEX_TIMER_INTR_STATUS__RESERVED_R 19
#define FLEX_TIMER_INTR_STATUS_WIDTH 19
#define FLEX_TIMER_INTR_STATUS__WIDTH 19
#define FLEX_TIMER_INTR_STATUS_ALL_L 18
#define FLEX_TIMER_INTR_STATUS_ALL_R 0
#define FLEX_TIMER_INTR_STATUS__ALL_L 18
#define FLEX_TIMER_INTR_STATUS__ALL_R 0
#define FLEX_TIMER_INTR_STATUS_DATAMASK 0x0007ffff
#define FLEX_TIMER_INTR_STATUS_RESETVALUE 0x0
#define FLEX_TIMER_INTR_MASK 0x440c0808
#define FLEX_TIMER_INTR_MASK_BASE 0x808
#define FLEX_TIMER_INTR_MASK_OFFSET 0x440c0808
#define FLEX_TIMER_INTR_MASK__intr_mask_L 18
#define FLEX_TIMER_INTR_MASK__intr_mask_R 0
#define FLEX_TIMER_INTR_MASK__intr_mask_WIDTH 19
#define FLEX_TIMER_INTR_MASK__intr_mask_RESETVALUE 0x0
#define FLEX_TIMER_INTR_MASK__RESERVED_L 31
#define FLEX_TIMER_INTR_MASK__RESERVED_R 19
#define FLEX_TIMER_INTR_MASK_WIDTH 19
#define FLEX_TIMER_INTR_MASK__WIDTH 19
#define FLEX_TIMER_INTR_MASK_ALL_L 18
#define FLEX_TIMER_INTR_MASK_ALL_R 0
#define FLEX_TIMER_INTR_MASK__ALL_L 18
#define FLEX_TIMER_INTR_MASK__ALL_R 0
#define FLEX_TIMER_INTR_MASK_DATAMASK 0x0007ffff
#define FLEX_TIMER_INTR_MASK_RESETVALUE 0x0
#define FLEX_TIMER_CTRL1 0x440c080c
#define FLEX_TIMER_CTRL1_BASE 0x80c
#define FLEX_TIMER_CTRL1_OFFSET 0x440c080c
#define FLEX_TIMER_CTRL1__timeout_config_L 31
#define FLEX_TIMER_CTRL1__timeout_config_R 12
#define FLEX_TIMER_CTRL1__timeout_config_WIDTH 20
#define FLEX_TIMER_CTRL1__timeout_config_RESETVALUE 0xfffff
#define FLEX_TIMER_CTRL1__timeout_en_L 11
#define FLEX_TIMER_CTRL1__timeout_en_R 11
#define FLEX_TIMER_CTRL1__timeout_en 11
#define FLEX_TIMER_CTRL1__timeout_en_WIDTH 1
#define FLEX_TIMER_CTRL1__timeout_en_RESETVALUE 0x0
#define FLEX_TIMER_CTRL1__dma_en_L 10
#define FLEX_TIMER_CTRL1__dma_en_R 8
#define FLEX_TIMER_CTRL1__dma_en_WIDTH 3
#define FLEX_TIMER_CTRL1__dma_en_RESETVALUE 0x0
#define FLEX_TIMER_CTRL1__ts_edge_HL_L 6
#define FLEX_TIMER_CTRL1__ts_edge_HL_R 4
#define FLEX_TIMER_CTRL1__ts_edge_HL_WIDTH 3
#define FLEX_TIMER_CTRL1__ts_edge_HL_RESETVALUE 0x0
#define FLEX_TIMER_CTRL1__ts_edge_LH_L 2
#define FLEX_TIMER_CTRL1__ts_edge_LH_R 0
#define FLEX_TIMER_CTRL1__ts_edge_LH_WIDTH 3
#define FLEX_TIMER_CTRL1__ts_edge_LH_RESETVALUE 0x0
#define FLEX_TIMER_CTRL1_WIDTH 32
#define FLEX_TIMER_CTRL1__WIDTH 32
#define FLEX_TIMER_CTRL1_ALL_L 31
#define FLEX_TIMER_CTRL1_ALL_R 0
#define FLEX_TIMER_CTRL1__ALL_L 31
#define FLEX_TIMER_CTRL1__ALL_R 0
#define FLEX_TIMER_CTRL1_DATAMASK 0xffffff77
#define FLEX_TIMER_CTRL1_RESETVALUE 0xfffff000
#define FLEX_TIMER_CTRL2 0x440c0810
#define FLEX_TIMER_CTRL2_BASE 0x810
#define FLEX_TIMER_CTRL2_OFFSET 0x440c0810
#define FLEX_TIMER_CTRL2__glitch_filter_disable_L 26
#define FLEX_TIMER_CTRL2__glitch_filter_disable_R 26
#define FLEX_TIMER_CTRL2__glitch_filter_disable 26
#define FLEX_TIMER_CTRL2__glitch_filter_disable_WIDTH 1
#define FLEX_TIMER_CTRL2__glitch_filter_disable_RESETVALUE 0x1
#define FLEX_TIMER_CTRL2__dma_burst_size_L 25
#define FLEX_TIMER_CTRL2__dma_burst_size_R 24
#define FLEX_TIMER_CTRL2__dma_burst_size_WIDTH 2
#define FLEX_TIMER_CTRL2__dma_burst_size_RESETVALUE 0x0
#define FLEX_TIMER_CTRL2__watermark2_L 21
#define FLEX_TIMER_CTRL2__watermark2_R 16
#define FLEX_TIMER_CTRL2__watermark2_WIDTH 6
#define FLEX_TIMER_CTRL2__watermark2_RESETVALUE 0x3f
#define FLEX_TIMER_CTRL2__watermark1_L 13
#define FLEX_TIMER_CTRL2__watermark1_R 8
#define FLEX_TIMER_CTRL2__watermark1_WIDTH 6
#define FLEX_TIMER_CTRL2__watermark1_RESETVALUE 0x3f
#define FLEX_TIMER_CTRL2__watermark0_L 5
#define FLEX_TIMER_CTRL2__watermark0_R 0
#define FLEX_TIMER_CTRL2__watermark0_WIDTH 6
#define FLEX_TIMER_CTRL2__watermark0_RESETVALUE 0x3f
#define FLEX_TIMER_CTRL2__RESERVED_0_L 31
#define FLEX_TIMER_CTRL2__RESERVED_0_R 27
#define FLEX_TIMER_CTRL2__RESERVED_1_L 23
#define FLEX_TIMER_CTRL2__RESERVED_1_R 22
#define FLEX_TIMER_CTRL2__RESERVED_2_L 15
#define FLEX_TIMER_CTRL2__RESERVED_2_R 14
#define FLEX_TIMER_CTRL2__RESERVED_3_L 7
#define FLEX_TIMER_CTRL2__RESERVED_3_R 6
#define FLEX_TIMER_CTRL2__RESERVED_L 31
#define FLEX_TIMER_CTRL2__RESERVED_R 27
#define FLEX_TIMER_CTRL2_WIDTH 27
#define FLEX_TIMER_CTRL2__WIDTH 27
#define FLEX_TIMER_CTRL2_ALL_L 26
#define FLEX_TIMER_CTRL2_ALL_R 0
#define FLEX_TIMER_CTRL2__ALL_L 26
#define FLEX_TIMER_CTRL2__ALL_R 0
#define FLEX_TIMER_CTRL2_DATAMASK 0x073f3f3f
#define FLEX_TIMER_CTRL2_RESETVALUE 0x43f3f3f
#define FLEX_TIMER_STATUS0 0x440c0814
#define FLEX_TIMER_STATUS0_BASE 0x814
#define FLEX_TIMER_STATUS0_OFFSET 0x440c0814
#define FLEX_TIMER_STATUS0__buffer_depth_L 15
#define FLEX_TIMER_STATUS0__buffer_depth_R 8
#define FLEX_TIMER_STATUS0__buffer_depth_WIDTH 8
#define FLEX_TIMER_STATUS0__buffer_depth_RESETVALUE 0x40
#define FLEX_TIMER_STATUS0__valid_enteries_L 7
#define FLEX_TIMER_STATUS0__valid_enteries_R 0
#define FLEX_TIMER_STATUS0__valid_enteries_WIDTH 8
#define FLEX_TIMER_STATUS0__valid_enteries_RESETVALUE 0x00
#define FLEX_TIMER_STATUS0__RESERVED_L 31
#define FLEX_TIMER_STATUS0__RESERVED_R 16
#define FLEX_TIMER_STATUS0_WIDTH 16
#define FLEX_TIMER_STATUS0__WIDTH 16
#define FLEX_TIMER_STATUS0_ALL_L 15
#define FLEX_TIMER_STATUS0_ALL_R 0
#define FLEX_TIMER_STATUS0__ALL_L 15
#define FLEX_TIMER_STATUS0__ALL_R 0
#define FLEX_TIMER_STATUS0_DATAMASK 0x0000ffff
#define FLEX_TIMER_STATUS0_RESETVALUE 0x4000
#define FLEX_TIMER_STATUS1 0x440c0818
#define FLEX_TIMER_STATUS1_BASE 0x818
#define FLEX_TIMER_STATUS1_OFFSET 0x440c0818
#define FLEX_TIMER_STATUS1__buffer_depth_L 15
#define FLEX_TIMER_STATUS1__buffer_depth_R 8
#define FLEX_TIMER_STATUS1__buffer_depth_WIDTH 8
#define FLEX_TIMER_STATUS1__buffer_depth_RESETVALUE 0x40
#define FLEX_TIMER_STATUS1__valid_enteries_L 7
#define FLEX_TIMER_STATUS1__valid_enteries_R 0
#define FLEX_TIMER_STATUS1__valid_enteries_WIDTH 8
#define FLEX_TIMER_STATUS1__valid_enteries_RESETVALUE 0x00
#define FLEX_TIMER_STATUS1__RESERVED_L 31
#define FLEX_TIMER_STATUS1__RESERVED_R 16
#define FLEX_TIMER_STATUS1_WIDTH 16
#define FLEX_TIMER_STATUS1__WIDTH 16
#define FLEX_TIMER_STATUS1_ALL_L 15
#define FLEX_TIMER_STATUS1_ALL_R 0
#define FLEX_TIMER_STATUS1__ALL_L 15
#define FLEX_TIMER_STATUS1__ALL_R 0
#define FLEX_TIMER_STATUS1_DATAMASK 0x0000ffff
#define FLEX_TIMER_STATUS1_RESETVALUE 0x4000
#define FLEX_TIMER_STATUS2 0x440c081c
#define FLEX_TIMER_STATUS2_BASE 0x81c
#define FLEX_TIMER_STATUS2_OFFSET 0x440c081c
#define FLEX_TIMER_STATUS2__buffer_depth_L 15
#define FLEX_TIMER_STATUS2__buffer_depth_R 8
#define FLEX_TIMER_STATUS2__buffer_depth_WIDTH 8
#define FLEX_TIMER_STATUS2__buffer_depth_RESETVALUE 0x40
#define FLEX_TIMER_STATUS2__valid_enteries_L 7
#define FLEX_TIMER_STATUS2__valid_enteries_R 0
#define FLEX_TIMER_STATUS2__valid_enteries_WIDTH 8
#define FLEX_TIMER_STATUS2__valid_enteries_RESETVALUE 0x00
#define FLEX_TIMER_STATUS2__RESERVED_L 31
#define FLEX_TIMER_STATUS2__RESERVED_R 16
#define FLEX_TIMER_STATUS2_WIDTH 16
#define FLEX_TIMER_STATUS2__WIDTH 16
#define FLEX_TIMER_STATUS2_ALL_L 15
#define FLEX_TIMER_STATUS2_ALL_R 0
#define FLEX_TIMER_STATUS2__ALL_L 15
#define FLEX_TIMER_STATUS2__ALL_R 0
#define FLEX_TIMER_STATUS2_DATAMASK 0x0000ffff
#define FLEX_TIMER_STATUS2_RESETVALUE 0x4000
#define FLEX_TIMER_DATA_REG0 0x440c0820
#define FLEX_TIMER_DATA_REG0_BASE 0x820
#define FLEX_TIMER_DATA_REG0_OFFSET 0x440c0820
#define FLEX_TIMER_DATA_REG0__Flex0_data_L 31
#define FLEX_TIMER_DATA_REG0__Flex0_data_R 0
#define FLEX_TIMER_DATA_REG0__Flex0_data_WIDTH 32
#define FLEX_TIMER_DATA_REG0__Flex0_data_RESETVALUE 0x00000000
#define FLEX_TIMER_DATA_REG0_WIDTH 32
#define FLEX_TIMER_DATA_REG0__WIDTH 32
#define FLEX_TIMER_DATA_REG0_ALL_L 31
#define FLEX_TIMER_DATA_REG0_ALL_R 0
#define FLEX_TIMER_DATA_REG0__ALL_L 31
#define FLEX_TIMER_DATA_REG0__ALL_R 0
#define FLEX_TIMER_DATA_REG0_DATAMASK 0xffffffff
#define FLEX_TIMER_DATA_REG0_RESETVALUE 0x0
#define FLEX_TIMER_DATA_REG1 0x440c0824
#define FLEX_TIMER_DATA_REG1_BASE 0x824
#define FLEX_TIMER_DATA_REG1_OFFSET 0x440c0824
#define FLEX_TIMER_DATA_REG1__Flex1_data_L 31
#define FLEX_TIMER_DATA_REG1__Flex1_data_R 0
#define FLEX_TIMER_DATA_REG1__Flex1_data_WIDTH 32
#define FLEX_TIMER_DATA_REG1__Flex1_data_RESETVALUE 0x00000000
#define FLEX_TIMER_DATA_REG1_WIDTH 32
#define FLEX_TIMER_DATA_REG1__WIDTH 32
#define FLEX_TIMER_DATA_REG1_ALL_L 31
#define FLEX_TIMER_DATA_REG1_ALL_R 0
#define FLEX_TIMER_DATA_REG1__ALL_L 31
#define FLEX_TIMER_DATA_REG1__ALL_R 0
#define FLEX_TIMER_DATA_REG1_DATAMASK 0xffffffff
#define FLEX_TIMER_DATA_REG1_RESETVALUE 0x0
#define FLEX_TIMER_DATA_REG2 0x440c0828
#define FLEX_TIMER_DATA_REG2_BASE 0x828
#define FLEX_TIMER_DATA_REG2_OFFSET 0x440c0828
#define FLEX_TIMER_DATA_REG2__Flex2_data_L 31
#define FLEX_TIMER_DATA_REG2__Flex2_data_R 0
#define FLEX_TIMER_DATA_REG2__Flex2_data_WIDTH 32
#define FLEX_TIMER_DATA_REG2__Flex2_data_RESETVALUE 0x00000000
#define FLEX_TIMER_DATA_REG2_WIDTH 32
#define FLEX_TIMER_DATA_REG2__WIDTH 32
#define FLEX_TIMER_DATA_REG2_ALL_L 31
#define FLEX_TIMER_DATA_REG2_ALL_R 0
#define FLEX_TIMER_DATA_REG2__ALL_L 31
#define FLEX_TIMER_DATA_REG2__ALL_R 0
#define FLEX_TIMER_DATA_REG2_DATAMASK 0xffffffff
#define FLEX_TIMER_DATA_REG2_RESETVALUE 0x0
#define FLEX_TIMER_REG8 0x440c082c
#define FLEX_TIMER_REG8_BASE 0x82c
#define FLEX_TIMER_REG8_OFFSET 0x440c082c
#define FLEX_TIMER_REG8__reserved_L 31
#define FLEX_TIMER_REG8__reserved_R 0
#define FLEX_TIMER_REG8__reserved_WIDTH 32
#define FLEX_TIMER_REG8__reserved_RESETVALUE 0x00000000
#define FLEX_TIMER_REG8_WIDTH 32
#define FLEX_TIMER_REG8__WIDTH 32
#define FLEX_TIMER_REG8_ALL_L 31
#define FLEX_TIMER_REG8_ALL_R 0
#define FLEX_TIMER_REG8__ALL_L 31
#define FLEX_TIMER_REG8__ALL_R 0
#define FLEX_TIMER_REG8_DATAMASK 0xffffffff
#define FLEX_TIMER_REG8_RESETVALUE 0x0

#ifdef __cplusplus
}
#endif

#endif
