obj-$(CONFIG_BRCM_DRIVER_SCC) += test_sc_main.o
obj-$(CONFIG_BRCM_DRIVER_SCC) += test_sc_infra.o
obj-$(CONFIG_BRCM_DRIVER_SCC) += test_sc_states.o
obj-$(CONFIG_BRCM_DRIVER_SCC) += emv2000/test_emv2000_t0.o
obj-$(CONFIG_BRCM_DRIVER_SCC) += emv2000/test_emv2000_t1.o
obj-$(CONFIG_BRCM_DRIVER_SCC) += emv2000/test_emv2000_tests.o
obj-$(CONFIG_BRCM_DRIVER_SCC) += test_sc_card.o

-include $(ZEPHYR_BASE)/tests/Makefile.test
-include $(MPOS_BASE)/Makefile.inc

