obj-y += crypto_rng.o
obj-y += crypto_selftest.o
obj-y += crypto_smau.o
obj-y += crypto_symmetric.o
obj-y += gf8_func.o


obj-$(CONFIG_CRYPTO_BRCM_MBEDTLS) += mbedtls/
-include $(MPOS_BASE)/Makefile.inc
