################################################
#
# Copyright Broadcom corporation (2017)
#
# Makefile for stubs sub directory
#
# Contains empty header files
# and a stub.c header file for misc items.
# Planned to be removed once all external
# dependencies are resolved.
###############################################
obj-y += stub.o
###############################################

-include $(MPOS_BASE)/Makefile.inc
