################################################
#
# Copyright Broadcom corporation (2017)
#
# Makefile for cvclass driver
#
# Files common across SBI and AAI
# Internal differences based on CFLAGS
###############################################
obj-y += cvinterface.o
obj-y += cvclass.o
###############################################

-include $(MPOS_BASE)/Makefile.inc
