################################################
#
# Copyright Broadcom corporation (2017)
#
# Makefile for dummy USBDCV class driver
#
# Files common across SBI and AAI
# Internal differences based on CFLAGS
###############################################
	obj-y += cvclass.o
	obj-y += cvglobalvar.o
###############################################

-include $(MPOS_BASE)/Makefile.inc