################################################
#
# Copyright Broadcom corporation (2017)
#
# Entry Point For USB Build
# All relevant include paths, subdirs and cflags
# to be added here.
################################################

obj-y += usbhost/

obj-$(CONFIG_BRCM_DRIVER_USDB) += usbd/

-include $(MPOS_BASE)/Makefile.inc
