/*
 * $Copyright Broadcom Corporation$
 *
 */
/*******************************************************************
 *
 *  Copyright 2013
 *  Broadcom Corporation
 *  5300 California Ave
 *  Irvine CA 92617
 *
 *  Broadcom provides the current code only to licensees who
 *  may have the non-exclusive right to use or modify this
 *  code according to the license.
 *  This program may be not sold, resold or disseminated in
 *  any form without the explicit consent from Broadcom Corp
 *
 *******************************************************************
 *
 *  Broadcom iProc Project
 *  File: iproc_sw.h
 *  Description: the main header file
 *
 *  $Copyright (C) 2013 Broadcom Corporation$
 *
 *  Version: $Id: $
 *
 *****************************************************************************/



#ifndef _IPROC_SW_H_
#define _IPROC_SW_H_

/* define compiler specific symbols */
#if defined ( __CC_ARM )
//#define __INLINE __inline /*!< inline keyword for armcc */
#define __INLINE /* Temporarily - to get code to compile */
#elif defined ( __GNUC__ )
#define __INLINE inline 	/*!< inline keyword for gcc */
#endif

/**********************************************************************
 *  Status Codes
 **********************************************************************/
typedef enum iproc_status_code {
	IPROC_STATUS_OK									= 0,
	IPROC_STATUS_OK_NEED_DMA						= 1,
	IPROC_STATUS_FAIL								= 100,

	IPROC_EXCEPTION_UNDEFINED_INSTRUCTION			= 200,
	IPROC_EXCEPTION_SOFTWARE_INTERRUPT				= 201,
	IPROC_EXCEPTION_PREFETCH_ABORT					= 202,
	IPROC_EXCEPTION_DATA_ABORT						= 203,
	IPROC_EXCEPTION_RESERVED						= 204,
	IPROC_EXCEPTION_IRQ								= 205,
	IPROC_EXCEPTION_FIQ								= 206,
    
	IPROC_EXCEPTION_NMI								= 207,
    IPROC_EXCEPTION_HARD_FAULT						= 208,
    IPROC_EXCEPTION_MEM								= 209,
    IPROC_EXCEPTION_BUS_FAULT						= 210,
    IPROC_EXCEPTION_USAGE							= 211,
    IPROC_EXCEPTION_SVC								= 212,
    IPROC_EXCEPTION_DEBUG							= 213,
    IPROC_EXCEPTION_PENDSV							= 214,
    IPROC_EXCEPTION_SYSTICK							= 215,
    IPROC_EXCEPTION_DEFAULT							= 216,

    IPROC_STATUS_NO_DEVICE							= 350,
	IPROC_STATUS_PARAMETER_INVALID,

	IPROC_STATUS_INVALID_PRIMARY_BOOTADDR,

    IPROC_STATUS_SELFTEST_FAIL						= 400,
    IPROC_STATUS_SELFTEST_AES_FAIL,
    IPROC_STATUS_SELFTEST_SHA256_FAIL,
    IPROC_STATUS_SELFTEST_RSA_FAIL,
    IPROC_STATUS_SELFTEST_ECDSA_VERIFY_FAIL,
	IPROC_STATUS_SELFTEST_RNG_FAIL,

	IPROC_STATUS_SOTP_UNPROG						= 420,

	IPROC_STATUS_BTROM_SYM_VERIFY_NOTALLOW			= 450,				/* BOOTROM */
    IPROC_STATUS_BTROM_RECOVERY_IMAGE_FAIL,
    IPROC_STATUS_BTROM_BTSRC_BOUNDARY_CHECK_FAIL,
    IPROC_STATUS_BTROM_SYM_AUTH_DISABLED,
	IPROC_STATUS_BTROM_RSA_AUTH_DISABLED,
	IPROC_STATUS_BTROM_ECDSA_AUTH_DISABLED,
	IPROC_STATUS_SBLCONFIG_RSA_INVALID_KBASE,
	IPROC_STATUS_SBLCONFIG_ECDSA_INVALID_KBASE,
	IPROC_STATUS_BTROM_AES128_ENCR_DISABLED,
	IPROC_STATUS_BTROM_AES256_ENCR_DISABLED,
	IPROC_STATUS_SOTP_INVALID,
	IPROC_STATUS_SOTP_DAUTH_INVALID,
	IPROC_STATUS_SOTP_KAES_INVALID,
	IPROC_STATUS_SOTP_CUST_ID_INVALID,
	IPROC_STATUS_BTROM_DBA_DISABLED,

	IPROC_STATUS_SBI_MAGIC_NOTMATCH_UNAUTH			= 600,				/* unauthenticated SBI header magic does not match */
	IPROC_STATUS_SBI_MAGIC_NOTMATCH_AUTH,								/* authenticated SBI header magic does not match */
	IPROC_STATUS_SBI_INVALID_SBI_TAG,
	IPROC_STATUS_SBI_INVALID_SBI_LENGTH,
	IPROC_STATUS_SBI_CHAIN_OF_TRUST_FAIL,
	IPROC_STATUS_SBI_HASH_NOTMATCH,  											/* auth fail: local hmac-sha256 key */
	IPROC_STATUS_SBI_SBIREVID_NOTMATCH,
	IPROC_STATUS_SBI_CUST_ID_NOTMATCH,
	IPROC_STATUS_SBI_CUST_REV_NOTMATCH,
	IPROC_STATUS_SBI_PRODUCT_ID_NOTMATCH,
	IPROC_STATUS_SBI_BRCM_REV_ID_NOTMATCH			= 610,
    IPROC_STATUS_SBI_NO_IMAGE,
    IPROC_STATUS_SBI_SIZE_TOO_BIG,
	IPROC_STATUS_SBI_NO_CHAIN,
	IPROC_STATUS_SBI_CHAIN_BTROM_REV_NOTMATCH,
    IPROC_STATUS_SBI_CHAIN_CUST_ID_NOTMATCH,
    IPROC_STATUS_SBI_CHAIN_CUST_REV_NOTMATCH,
	IPROC_STATUS_SBI_CHAIN_CUST_REV_NOTMATCH_BRCM,
	IPROC_STATUS_SBI_OFFSET_NOTALIGN,									/* SBI header offsets not aligned (auth payload offset and sbi code offset */
	IPROC_STATUS_SBI_NO_DAUTH,
	IPROC_STATUS_SBI_DAUTH_HASH_NOTMATCH			= 620,
	IPROC_STATUS_SBI_STARTVEC_NOTALIGN,
	IPROC_STATUS_SBI_UNAUTH_HDR_CRC_FAIL,
	IPROC_STATUS_BBL_KEK_INVALID,
	IPROC_STATUS_SBI_INVALID_VERIFICATION_CONFIG_SIGNATURE_HASHALG,
	IPROC_STATUS_SBI_INVALID_VERIFICATION_CONFIG_HMAC_HASHALG,
	IPROC_STATUS_SBI_INVALID_SIZE_HMAC_HASHALG,
	IPROC_STATUS_SBI_INVALID_VERIFICATION_CONFIG_SIGNATURE_SCHEME,
	IPROC_STATUS_SBI_INVALID_DAUTH_KEYALGORITHM,
	IPROC_STATUS_SBI_INVALID_DAUTH_KEYINFO,
	IPROC_STATUS_SBI_HMAC_SHA256_NOTMATCH,

	IPROC_STATUS_TOC_OR_SBI_NOTFOUND,

   /* Auth Header sanity check */
   IPROC_AUTH_HEADER_VERIFY_FAILED					= 1200,
   IPROC_STATUS_AUTH_HEADER_VERIFY_FAILED_AUTHLENGTH,
   IPROC_STATUS_AUTH_HEADER_VERIFY_FAILED_NCOTENTRIES,
   IPROC_STATUS_AUTH_HEADER_VERIFY_FAILED_BOOTLOADEROFFSET,
   IPROC_STATUS_AUTH_HEADER_VERIFY_FAILED_BOOTLOADERLENGTH,
   IPROC_STATUS_AUTH_HEADER_VERIFY_FAILED_COTOFFSET,
   IPROC_STATUS_AUTH_HEADER_VERIFY_FAILED_AUTHENTICATIONOFFSET,
   IPROC_STATUS_SBICONFIG_INVALID_AUTHENTICATE_INPLACE,
   IPROC_INVALID_MONT_CTX_LENGTH,
   IPROC_INVALID_KEY_SIZE,
   IPROC_4K_NO_MONT_UNSUPPORTED,
   IPROC_INVALID_SIGNATURE_SIZE,
   IPROC_2K_TO_4K_UNSUPPORTED,
   IPROC_INVALID_KEY,
   IPROC_STATUS_SBL_INVALID_ENC_DEVTYPE,
   IPROC_STATUS_UNAUTH_HEADER_NONAB_INVALID_SBIADDRESS,
   IPROC_STATUS_SBL_INVALID_POWER_STATUS,
   IPROC_STATUS_SBL_INVALID_AUTHTYPE_FOR_OPERATION,
   IPROC_STATUS_SBL_DAUTH_LENGTH_DOES_NOT_MATCH_EXPECTED_LENGTH,
   IPROC_STATUS_SBL_INVALID_COT_OFFSET
} IPROC_STATUS;

#endif  /* _IPROC_SW_H_ */

