/******************************************************************************
 *  Copyright (c) 2005-2018 Broadcom. All Rights Reserved. The term "Broadcom"
 *  refers to Broadcom Inc. and/or its subsidiaries.
 *
 *  This program is the proprietary software of Broadcom and/or its licensors,
 *  and may only be used, duplicated, modified or distributed pursuant to the
 *  terms and conditions of a separate, written license agreement executed
 *  between you and Broadcom (an "Authorized License").  Except as set forth in
 *  an Authorized License, Broadcom grants no license (express or implied),
 *  right to use, or waiver of any kind with respect to the Software, and
 *  Broadcom expressly reserves all rights in and to the Software and all
 *  intellectual property rights therein.  IF YOU HAVE NO AUTHORIZED LICENSE,
 *  THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 *  IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 *  Except as expressly set forth in the Authorized License,
 *
 *  1.     This program, including its structure, sequence and organization,
 *  constitutes the valuable trade secrets of Broadcom, and you shall use all
 *  reasonable efforts to protect the confidentiality thereof, and to use this
 *  information only in connection with your use of Broadcom integrated circuit
 *  products.
 *
 *  2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 *  "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 *  OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 *  RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 *  IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR A
 *  PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 *  ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME THE
 *  ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 *  3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM OR
 *  ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 *  INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 *  RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 *  HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 *  EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 *  WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 *  FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/

#ifndef __REGS_H__
#define __REGS_H__

#define SOTP_REGS_CHIP_CTRL__SW_AB_DEV_MODE_L 9
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEV_MODE_R 9
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEV_MODE 9
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEV_MODE_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEV_MODE_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEVICE_L 8
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEVICE_R 8
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEVICE 8
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEVICE_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__SW_AB_DEVICE_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__SW_NON_AB_DEVICE_L 7
#define SOTP_REGS_CHIP_CTRL__SW_NON_AB_DEVICE_R 7
#define SOTP_REGS_CHIP_CTRL__SW_NON_AB_DEVICE 7
#define SOTP_REGS_CHIP_CTRL__SW_NON_AB_DEVICE_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__SW_NON_AB_DEVICE_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__SW_CID_PROG_L 6
#define SOTP_REGS_CHIP_CTRL__SW_CID_PROG_R 6
#define SOTP_REGS_CHIP_CTRL__SW_CID_PROG 6
#define SOTP_REGS_CHIP_CTRL__SW_CID_PROG_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__SW_CID_PROG_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__SW_MANU_PROG_L 5
#define SOTP_REGS_CHIP_CTRL__SW_MANU_PROG_R 5
#define SOTP_REGS_CHIP_CTRL__SW_MANU_PROG 5
#define SOTP_REGS_CHIP_CTRL__SW_MANU_PROG_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__SW_MANU_PROG_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__SW_OVERRIDE_CHIP_STATES_L 4
#define SOTP_REGS_CHIP_CTRL__SW_OVERRIDE_CHIP_STATES_R 4
#define SOTP_REGS_CHIP_CTRL__SW_OVERRIDE_CHIP_STATES 4
#define SOTP_REGS_CHIP_CTRL__SW_OVERRIDE_CHIP_STATES_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__SW_OVERRIDE_CHIP_STATES_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__CLEAR_SYSCTRL_ALL_MASTER_NS_L 0
#define SOTP_REGS_CHIP_CTRL__CLEAR_SYSCTRL_ALL_MASTER_NS_R 0
#define SOTP_REGS_CHIP_CTRL__CLEAR_SYSCTRL_ALL_MASTER_NS 0
#define SOTP_REGS_CHIP_CTRL__CLEAR_SYSCTRL_ALL_MASTER_NS_WIDTH 1
#define SOTP_REGS_CHIP_CTRL__CLEAR_SYSCTRL_ALL_MASTER_NS_RESETVALUE 0x0
#define SOTP_REGS_CHIP_CTRL__RESERVED_L 31
#define SOTP_REGS_CHIP_CTRL__RESERVED_R 10
#define SOTP_REGS_CHIP_CTRL_WIDTH 10
#define SOTP_REGS_CHIP_CTRL__WIDTH 10
#define SOTP_REGS_CHIP_CTRL_ALL_L 9
#define SOTP_REGS_CHIP_CTRL_ALL_R 0
#define SOTP_REGS_CHIP_CTRL__ALL_L 9
#define SOTP_REGS_CHIP_CTRL__ALL_R 0
#define SOTP_REGS_CHIP_CTRL_DATAMASK 0x000003f1
#define SOTP_REGS_CHIP_CTRL_RESETVALUE 0x0

#define IPROC_CRMU_MAIL_BOX0 0x30024028
#define IPROC_CRMU_MAIL_BOX1 0x3002402c

#define CDRU_SW_RESET_CTRL 0x3001d090
#define CDRU_SW_RESET_CTRL_BASE 0x090
#define CDRU_SW_RESET_CTRL_OFFSET 0x3001d090
#define CDRU_SW_RESET_CTRL__seu_sw_reset_n_L 30
#define CDRU_SW_RESET_CTRL__seu_sw_reset_n_R 30
#define CDRU_SW_RESET_CTRL__seu_sw_reset_n 30
#define CDRU_SW_RESET_CTRL__seu_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__seu_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__wdt_sw_reset_n_L 29
#define CDRU_SW_RESET_CTRL__wdt_sw_reset_n_R 29
#define CDRU_SW_RESET_CTRL__wdt_sw_reset_n 29
#define CDRU_SW_RESET_CTRL__wdt_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__wdt_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__cm3_sw_reset_n_L 28
#define CDRU_SW_RESET_CTRL__cm3_sw_reset_n_R 28
#define CDRU_SW_RESET_CTRL__cm3_sw_reset_n 28
#define CDRU_SW_RESET_CTRL__cm3_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__cm3_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__idc_sw_reset_n_L 27
#define CDRU_SW_RESET_CTRL__idc_sw_reset_n_R 27
#define CDRU_SW_RESET_CTRL__idc_sw_reset_n 27
#define CDRU_SW_RESET_CTRL__idc_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__idc_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__smau_sw_reset_n_L 26
#define CDRU_SW_RESET_CTRL__smau_sw_reset_n_R 26
#define CDRU_SW_RESET_CTRL__smau_sw_reset_n 26
#define CDRU_SW_RESET_CTRL__smau_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__smau_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__dma_sw_reset_n_L 25
#define CDRU_SW_RESET_CTRL__dma_sw_reset_n_R 25
#define CDRU_SW_RESET_CTRL__dma_sw_reset_n 25
#define CDRU_SW_RESET_CTRL__dma_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__dma_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__usbd_sw_reset_n_L 24
#define CDRU_SW_RESET_CTRL__usbd_sw_reset_n_R 24
#define CDRU_SW_RESET_CTRL__usbd_sw_reset_n 24
#define CDRU_SW_RESET_CTRL__usbd_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__usbd_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__usbh_sw_reset_n_L 23
#define CDRU_SW_RESET_CTRL__usbh_sw_reset_n_R 23
#define CDRU_SW_RESET_CTRL__usbh_sw_reset_n 23
#define CDRU_SW_RESET_CTRL__usbh_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__usbh_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__smc_sw_reset_n_L 22
#define CDRU_SW_RESET_CTRL__smc_sw_reset_n_R 22
#define CDRU_SW_RESET_CTRL__smc_sw_reset_n 22
#define CDRU_SW_RESET_CTRL__smc_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__smc_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__sram_sw_reset_n_L 21
#define CDRU_SW_RESET_CTRL__sram_sw_reset_n_R 21
#define CDRU_SW_RESET_CTRL__sram_sw_reset_n 21
#define CDRU_SW_RESET_CTRL__sram_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__sram_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__rom_sw_reset_n_L 20
#define CDRU_SW_RESET_CTRL__rom_sw_reset_n_R 20
#define CDRU_SW_RESET_CTRL__rom_sw_reset_n 20
#define CDRU_SW_RESET_CTRL__rom_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__rom_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__qspi_sw_reset_n_L 19
#define CDRU_SW_RESET_CTRL__qspi_sw_reset_n_R 19
#define CDRU_SW_RESET_CTRL__qspi_sw_reset_n 19
#define CDRU_SW_RESET_CTRL__qspi_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__qspi_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__spi1_sw_reset_n_L 18
#define CDRU_SW_RESET_CTRL__spi1_sw_reset_n_R 18
#define CDRU_SW_RESET_CTRL__spi1_sw_reset_n 18
#define CDRU_SW_RESET_CTRL__spi1_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__spi1_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__spi2_sw_reset_n_L 17
#define CDRU_SW_RESET_CTRL__spi2_sw_reset_n_R 17
#define CDRU_SW_RESET_CTRL__spi2_sw_reset_n 17
#define CDRU_SW_RESET_CTRL__spi2_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__spi2_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__spi3_sw_reset_n_L 16
#define CDRU_SW_RESET_CTRL__spi3_sw_reset_n_R 16
#define CDRU_SW_RESET_CTRL__spi3_sw_reset_n 16
#define CDRU_SW_RESET_CTRL__spi3_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__spi3_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__spi4_sw_reset_n_L 15
#define CDRU_SW_RESET_CTRL__spi4_sw_reset_n_R 15
#define CDRU_SW_RESET_CTRL__spi4_sw_reset_n 15
#define CDRU_SW_RESET_CTRL__spi4_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__spi4_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__spi5_sw_reset_n_L 14
#define CDRU_SW_RESET_CTRL__spi5_sw_reset_n_R 14
#define CDRU_SW_RESET_CTRL__spi5_sw_reset_n 14
#define CDRU_SW_RESET_CTRL__spi5_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__spi5_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__uart0_sw_reset_n_L 13
#define CDRU_SW_RESET_CTRL__uart0_sw_reset_n_R 13
#define CDRU_SW_RESET_CTRL__uart0_sw_reset_n 13
#define CDRU_SW_RESET_CTRL__uart0_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__uart0_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__uart1_sw_reset_n_L 12
#define CDRU_SW_RESET_CTRL__uart1_sw_reset_n_R 12
#define CDRU_SW_RESET_CTRL__uart1_sw_reset_n 12
#define CDRU_SW_RESET_CTRL__uart1_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__uart1_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__uart2_sw_reset_n_L 11
#define CDRU_SW_RESET_CTRL__uart2_sw_reset_n_R 11
#define CDRU_SW_RESET_CTRL__uart2_sw_reset_n 11
#define CDRU_SW_RESET_CTRL__uart2_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__uart2_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__uart3_sw_reset_n_L 10
#define CDRU_SW_RESET_CTRL__uart3_sw_reset_n_R 10
#define CDRU_SW_RESET_CTRL__uart3_sw_reset_n 10
#define CDRU_SW_RESET_CTRL__uart3_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__uart3_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__fsk_sw_reset_n_L 9
#define CDRU_SW_RESET_CTRL__fsk_sw_reset_n_R 9
#define CDRU_SW_RESET_CTRL__fsk_sw_reset_n 9
#define CDRU_SW_RESET_CTRL__fsk_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__fsk_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__pwm_sw_reset_n_L 8
#define CDRU_SW_RESET_CTRL__pwm_sw_reset_n_R 8
#define CDRU_SW_RESET_CTRL__pwm_sw_reset_n 8
#define CDRU_SW_RESET_CTRL__pwm_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__pwm_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__mdio_sw_reset_n_L 7
#define CDRU_SW_RESET_CTRL__mdio_sw_reset_n_R 7
#define CDRU_SW_RESET_CTRL__mdio_sw_reset_n 7
#define CDRU_SW_RESET_CTRL__mdio_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__mdio_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__timer0_sw_reset_n_L 6
#define CDRU_SW_RESET_CTRL__timer0_sw_reset_n_R 6
#define CDRU_SW_RESET_CTRL__timer0_sw_reset_n 6
#define CDRU_SW_RESET_CTRL__timer0_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__timer0_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__timer1_sw_reset_n_L 5
#define CDRU_SW_RESET_CTRL__timer1_sw_reset_n_R 5
#define CDRU_SW_RESET_CTRL__timer1_sw_reset_n 5
#define CDRU_SW_RESET_CTRL__timer1_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__timer1_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__sci_sw_reset_n_L 4
#define CDRU_SW_RESET_CTRL__sci_sw_reset_n_R 4
#define CDRU_SW_RESET_CTRL__sci_sw_reset_n 4
#define CDRU_SW_RESET_CTRL__sci_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__sci_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__gpio_sw_reset_n_L 3
#define CDRU_SW_RESET_CTRL__gpio_sw_reset_n_R 3
#define CDRU_SW_RESET_CTRL__gpio_sw_reset_n 3
#define CDRU_SW_RESET_CTRL__gpio_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__gpio_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__trng_sw_reset_n_L 2
#define CDRU_SW_RESET_CTRL__trng_sw_reset_n_R 2
#define CDRU_SW_RESET_CTRL__trng_sw_reset_n 2
#define CDRU_SW_RESET_CTRL__trng_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__trng_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__pka_sw_reset_n_L 1
#define CDRU_SW_RESET_CTRL__pka_sw_reset_n_R 1
#define CDRU_SW_RESET_CTRL__pka_sw_reset_n 1
#define CDRU_SW_RESET_CTRL__pka_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__pka_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__adc_sw_reset_n_L 0
#define CDRU_SW_RESET_CTRL__adc_sw_reset_n_R 0
#define CDRU_SW_RESET_CTRL__adc_sw_reset_n 0
#define CDRU_SW_RESET_CTRL__adc_sw_reset_n_WIDTH 1
#define CDRU_SW_RESET_CTRL__adc_sw_reset_n_RESETVALUE 0x1
#define CDRU_SW_RESET_CTRL__RESERVED 31
#define CDRU_SW_RESET_CTRL_WIDTH 31
#define CDRU_SW_RESET_CTRL__WIDTH 31
#define CDRU_SW_RESET_CTRL_ALL_L 30
#define CDRU_SW_RESET_CTRL_ALL_R 0
#define CDRU_SW_RESET_CTRL__ALL_L 30
#define CDRU_SW_RESET_CTRL__ALL_R 0
#define CDRU_SW_RESET_CTRL_DATAMASK 0x7fffffff
#define CDRU_SW_RESET_CTRL_RESETVALUE 0x7fffffff

#define CRMU_USBPHY_D_CTRL 0x3001c024
#define CRMU_USBPHY_D_CTRL_BASE 0x024
#define CRMU_USBPHY_D_CTRL_OFFSET 0x3001c024
#define CRMU_USBPHY_D_CTRL__phy_iso_L 20
#define CRMU_USBPHY_D_CTRL__phy_iso_R 20
#define CRMU_USBPHY_D_CTRL__phy_iso 20
#define CRMU_USBPHY_D_CTRL__phy_iso_WIDTH 1
#define CRMU_USBPHY_D_CTRL__phy_iso_RESETVALUE 0x1
#define CRMU_USBPHY_D_CTRL__pll_ndiv_frac_L 19
#define CRMU_USBPHY_D_CTRL__pll_ndiv_frac_R 0
#define CRMU_USBPHY_D_CTRL__pll_ndiv_frac_WIDTH 20
#define CRMU_USBPHY_D_CTRL__pll_ndiv_frac_RESETVALUE 0x66666
#define CRMU_USBPHY_D_CTRL__RESERVED_L 31
#define CRMU_USBPHY_D_CTRL__RESERVED_R 21
#define CRMU_USBPHY_D_CTRL_WIDTH 21
#define CRMU_USBPHY_D_CTRL__WIDTH 21
#define CRMU_USBPHY_D_CTRL_ALL_L 20
#define CRMU_USBPHY_D_CTRL_ALL_R 0
#define CRMU_USBPHY_D_CTRL__ALL_L 20
#define CRMU_USBPHY_D_CTRL__ALL_R 0
#define CRMU_USBPHY_D_CTRL_DATAMASK 0x001fffff
#define CRMU_USBPHY_D_CTRL_RESETVALUE 0x166666
#define CDRU_USBPHY_D_CTRL1 0x3001d0c4
#define CDRU_USBPHY_D_CTRL1_BASE 0x0c4
#define CDRU_USBPHY_D_CTRL1_OFFSET 0x3001d0c4
#define CDRU_USBPHY_D_CTRL1__pll_suspend_en_L 27
#define CDRU_USBPHY_D_CTRL1__pll_suspend_en_R 27
#define CDRU_USBPHY_D_CTRL1__pll_suspend_en 27
#define CDRU_USBPHY_D_CTRL1__pll_suspend_en_WIDTH 1
#define CDRU_USBPHY_D_CTRL1__pll_suspend_en_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL1__pll_resetb_L 26
#define CDRU_USBPHY_D_CTRL1__pll_resetb_R 26
#define CDRU_USBPHY_D_CTRL1__pll_resetb 26
#define CDRU_USBPHY_D_CTRL1__pll_resetb_WIDTH 1
#define CDRU_USBPHY_D_CTRL1__pll_resetb_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL1__kp_L 25
#define CDRU_USBPHY_D_CTRL1__kp_R 22
#define CDRU_USBPHY_D_CTRL1__kp_WIDTH 4
#define CDRU_USBPHY_D_CTRL1__kp_RESETVALUE 0x8
#define CDRU_USBPHY_D_CTRL1__ki_L 21
#define CDRU_USBPHY_D_CTRL1__ki_R 19
#define CDRU_USBPHY_D_CTRL1__ki_WIDTH 3
#define CDRU_USBPHY_D_CTRL1__ki_RESETVALUE 0x4
#define CDRU_USBPHY_D_CTRL1__ka_L 18
#define CDRU_USBPHY_D_CTRL1__ka_R 16
#define CDRU_USBPHY_D_CTRL1__ka_WIDTH 3
#define CDRU_USBPHY_D_CTRL1__ka_RESETVALUE 0x4
#define CDRU_USBPHY_D_CTRL1__ndiv_int_L 15
#define CDRU_USBPHY_D_CTRL1__ndiv_int_R 6
#define CDRU_USBPHY_D_CTRL1__ndiv_int_WIDTH 10
#define CDRU_USBPHY_D_CTRL1__ndiv_int_RESETVALUE 0x26
#define CDRU_USBPHY_D_CTRL1__pdiv_L 5
#define CDRU_USBPHY_D_CTRL1__pdiv_R 3
#define CDRU_USBPHY_D_CTRL1__pdiv_WIDTH 3
#define CDRU_USBPHY_D_CTRL1__pdiv_RESETVALUE 0x1
#define CDRU_USBPHY_D_CTRL1__resetb_L 2
#define CDRU_USBPHY_D_CTRL1__resetb_R 2
#define CDRU_USBPHY_D_CTRL1__resetb 2
#define CDRU_USBPHY_D_CTRL1__resetb_WIDTH 1
#define CDRU_USBPHY_D_CTRL1__resetb_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL1__utmi_l1_suspendm_L 1
#define CDRU_USBPHY_D_CTRL1__utmi_l1_suspendm_R 1
#define CDRU_USBPHY_D_CTRL1__utmi_l1_suspendm 1
#define CDRU_USBPHY_D_CTRL1__utmi_l1_suspendm_WIDTH 1
#define CDRU_USBPHY_D_CTRL1__utmi_l1_suspendm_RESETVALUE 0x1
#define CDRU_USBPHY_D_CTRL1__utmi_l1_sleepm_L 0
#define CDRU_USBPHY_D_CTRL1__utmi_l1_sleepm_R 0
#define CDRU_USBPHY_D_CTRL1__utmi_l1_sleepm 0
#define CDRU_USBPHY_D_CTRL1__utmi_l1_sleepm_WIDTH 1
#define CDRU_USBPHY_D_CTRL1__utmi_l1_sleepm_RESETVALUE 0x1
#define CDRU_USBPHY_D_CTRL1__RESERVED_L 31
#define CDRU_USBPHY_D_CTRL1__RESERVED_R 28
#define CDRU_USBPHY_D_CTRL1_WIDTH 28
#define CDRU_USBPHY_D_CTRL1__WIDTH 28
#define CDRU_USBPHY_D_CTRL1_ALL_L 27
#define CDRU_USBPHY_D_CTRL1_ALL_R 0
#define CDRU_USBPHY_D_CTRL1__ALL_L 27
#define CDRU_USBPHY_D_CTRL1__ALL_R 0
#define CDRU_USBPHY_D_CTRL1_DATAMASK 0x0fffffff
#define CDRU_USBPHY_D_CTRL1_RESETVALUE 0x224098b
#define CDRU_USBPHY_D_STATUS 0x3001d0c8
#define CDRU_USBPHY_D_STATUS_BASE 0x0c8
#define CDRU_USBPHY_D_STATUS_OFFSET 0x3001d0c8
#define CDRU_USBPHY_D_STATUS__pll_lock_L 0
#define CDRU_USBPHY_D_STATUS__pll_lock_R 0
#define CDRU_USBPHY_D_STATUS__pll_lock 0
#define CDRU_USBPHY_D_STATUS__pll_lock_WIDTH 1
#define CDRU_USBPHY_D_STATUS__pll_lock_RESETVALUE 0x0
#define CDRU_USBPHY_D_STATUS__RESERVED_L 31
#define CDRU_USBPHY_D_STATUS__RESERVED_R 1
#define CDRU_USBPHY_D_STATUS_WIDTH 1
#define CDRU_USBPHY_D_STATUS__WIDTH 1
#define CDRU_USBPHY_D_STATUS_ALL_L 0
#define CDRU_USBPHY_D_STATUS_ALL_R 0
#define CDRU_USBPHY_D_STATUS__ALL_L 0
#define CDRU_USBPHY_D_STATUS__ALL_R 0
#define CDRU_USBPHY_D_STATUS_DATAMASK 0x00000001
#define CDRU_USBPHY_D_STATUS_RESETVALUE 0x0
#define CDRU_USBPHY_D_P1CTRL 0x3001d0cc
#define CDRU_USBPHY_D_P1CTRL_BASE 0x0cc
#define CDRU_USBPHY_D_P1CTRL_OFFSET 0x3001d0cc
#define CDRU_USBPHY_D_P1CTRL__phy_p1ctrl_L 15
#define CDRU_USBPHY_D_P1CTRL__phy_p1ctrl_R 0
#define CDRU_USBPHY_D_P1CTRL__phy_p1ctrl_WIDTH 16
#define CDRU_USBPHY_D_P1CTRL__phy_p1ctrl_RESETVALUE 0x0005
#define CDRU_USBPHY_D_P1CTRL__RESERVED_L 31
#define CDRU_USBPHY_D_P1CTRL__RESERVED_R 16
#define CDRU_USBPHY_D_P1CTRL_WIDTH 16
#define CDRU_USBPHY_D_P1CTRL__WIDTH 16
#define CDRU_USBPHY_D_P1CTRL_ALL_L 15
#define CDRU_USBPHY_D_P1CTRL_ALL_R 0
#define CDRU_USBPHY_D_P1CTRL__ALL_L 15
#define CDRU_USBPHY_D_P1CTRL__ALL_R 0
#define CDRU_USBPHY_D_P1CTRL_DATAMASK 0x0000ffff
#define CDRU_USBPHY_D_P1CTRL_RESETVALUE 0x5
#define CDRU_USBPHY_D_CTRL2 0x3001d0d0
#define CDRU_USBPHY_D_CTRL2_BASE 0x0d0
#define CDRU_USBPHY_D_CTRL2_OFFSET 0x3001d0d0
#define CDRU_USBPHY_D_CTRL2__iddq_L 10
#define CDRU_USBPHY_D_CTRL2__iddq_R 10
#define CDRU_USBPHY_D_CTRL2__iddq 10
#define CDRU_USBPHY_D_CTRL2__iddq_WIDTH 1
#define CDRU_USBPHY_D_CTRL2__iddq_RESETVALUE 0x1
#define CDRU_USBPHY_D_CTRL2__pll_bypass_L 9
#define CDRU_USBPHY_D_CTRL2__pll_bypass_R 9
#define CDRU_USBPHY_D_CTRL2__pll_bypass 9
#define CDRU_USBPHY_D_CTRL2__pll_bypass_WIDTH 1
#define CDRU_USBPHY_D_CTRL2__pll_bypass_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL2__ldobg_outadj_L 8
#define CDRU_USBPHY_D_CTRL2__ldobg_outadj_R 5
#define CDRU_USBPHY_D_CTRL2__ldobg_outadj_WIDTH 4
#define CDRU_USBPHY_D_CTRL2__ldobg_outadj_RESETVALUE 0x4
#define CDRU_USBPHY_D_CTRL2__afeldocntl_L 4
#define CDRU_USBPHY_D_CTRL2__afeldocntl_R 2
#define CDRU_USBPHY_D_CTRL2__afeldocntl_WIDTH 3
#define CDRU_USBPHY_D_CTRL2__afeldocntl_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL2__afeldocntlen_L 1
#define CDRU_USBPHY_D_CTRL2__afeldocntlen_R 1
#define CDRU_USBPHY_D_CTRL2__afeldocntlen 1
#define CDRU_USBPHY_D_CTRL2__afeldocntlen_WIDTH 1
#define CDRU_USBPHY_D_CTRL2__afeldocntlen_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL2__ldo_pwrdwnb_L 0
#define CDRU_USBPHY_D_CTRL2__ldo_pwrdwnb_R 0
#define CDRU_USBPHY_D_CTRL2__ldo_pwrdwnb 0
#define CDRU_USBPHY_D_CTRL2__ldo_pwrdwnb_WIDTH 1
#define CDRU_USBPHY_D_CTRL2__ldo_pwrdwnb_RESETVALUE 0x0
#define CDRU_USBPHY_D_CTRL2__RESERVED_L 31
#define CDRU_USBPHY_D_CTRL2__RESERVED_R 11
#define CDRU_USBPHY_D_CTRL2_WIDTH 11
#define CDRU_USBPHY_D_CTRL2__WIDTH 11
#define CDRU_USBPHY_D_CTRL2_ALL_L 10
#define CDRU_USBPHY_D_CTRL2_ALL_R 0
#define CDRU_USBPHY_D_CTRL2__ALL_L 10
#define CDRU_USBPHY_D_CTRL2__ALL_R 0
#define CDRU_USBPHY_D_CTRL2_DATAMASK 0x000007ff
#define CDRU_USBPHY_D_CTRL2_RESETVALUE 0x480

#define SYS_CLK_SOURCE_SEL_CTRL 0x3001d038

#define DEVCONFIG 0x47000400
#define DEVCONFIG_BASE 0x400
#define DEVCONFIG_OFFSET 0x400
#define DEVCONFIG__LPM_EN_L 21
#define DEVCONFIG__LPM_EN_R 21
#define DEVCONFIG__LPM_EN 21
#define DEVCONFIG__LPM_EN_WIDTH 1
#define DEVCONFIG__LPM_EN_RESETVALUE 0x0
#define DEVCONFIG__LPM_AUTO_L 20
#define DEVCONFIG__LPM_AUTO_R 20
#define DEVCONFIG__LPM_AUTO 20
#define DEVCONFIG__LPM_AUTO_WIDTH 1
#define DEVCONFIG__LPM_AUTO_RESETVALUE 0x0
#define DEVCONFIG__DDR_L 19
#define DEVCONFIG__DDR_R 19
#define DEVCONFIG__DDR 19
#define DEVCONFIG__DDR_WIDTH 1
#define DEVCONFIG__DDR_RESETVALUE 0x0
#define DEVCONFIG__SET_DESC_L 18
#define DEVCONFIG__SET_DESC_R 18
#define DEVCONFIG__SET_DESC 18
#define DEVCONFIG__SET_DESC_WIDTH 1
#define DEVCONFIG__SET_DESC_RESETVALUE 0x0
#define DEVCONFIG__CSR_PRG_L 17
#define DEVCONFIG__CSR_PRG_R 17
#define DEVCONFIG__CSR_PRG 17
#define DEVCONFIG__CSR_PRG_WIDTH 1
#define DEVCONFIG__CSR_PRG_RESETVALUE 0x0
#define DEVCONFIG__HALT_STATUS_L 16
#define DEVCONFIG__HALT_STATUS_R 16
#define DEVCONFIG__HALT_STATUS 16
#define DEVCONFIG__HALT_STATUS_WIDTH 1
#define DEVCONFIG__HALT_STATUS_RESETVALUE 0x0
#define DEVCONFIG__HS_TIMEOUT_CALIB_L 15
#define DEVCONFIG__HS_TIMEOUT_CALIB_R 13
#define DEVCONFIG__HS_TIMEOUT_CALIB_WIDTH 3
#define DEVCONFIG__HS_TIMEOUT_CALIB_RESETVALUE 0x0
#define DEVCONFIG__FS_TIMEOUT_CALIB_L 12
#define DEVCONFIG__FS_TIMEOUT_CALIB_R 10
#define DEVCONFIG__FS_TIMEOUT_CALIB_WIDTH 3
#define DEVCONFIG__FS_TIMEOUT_CALIB_RESETVALUE 0x0
#define DEVCONFIG__PHY_ERROR_DETECT_L 9
#define DEVCONFIG__PHY_ERROR_DETECT_R 9
#define DEVCONFIG__PHY_ERROR_DETECT 9
#define DEVCONFIG__PHY_ERROR_DETECT_WIDTH 1
#define DEVCONFIG__PHY_ERROR_DETECT_RESETVALUE 0x0
#define DEVCONFIG__STATUS_1_L 8
#define DEVCONFIG__STATUS_1_R 8
#define DEVCONFIG__STATUS_1 8
#define DEVCONFIG__STATUS_1_WIDTH 1
#define DEVCONFIG__STATUS_1_RESETVALUE 0x0
#define DEVCONFIG__STATUS_L 7
#define DEVCONFIG__STATUS_R 7
#define DEVCONFIG__STATUS 7
#define DEVCONFIG__STATUS_WIDTH 1
#define DEVCONFIG__STATUS_RESETVALUE 0x0
#define DEVCONFIG__DIR_L 6
#define DEVCONFIG__DIR_R 6
#define DEVCONFIG__DIR 6
#define DEVCONFIG__DIR_WIDTH 1
#define DEVCONFIG__DIR_RESETVALUE 0x0
#define DEVCONFIG__PI_L 5
#define DEVCONFIG__PI_R 5
#define DEVCONFIG__PI 5
#define DEVCONFIG__PI_WIDTH 1
#define DEVCONFIG__PI_RESETVALUE 0x1
#define DEVCONFIG__SS_L 4
#define DEVCONFIG__SS_R 4
#define DEVCONFIG__SS 4
#define DEVCONFIG__SS_WIDTH 1
#define DEVCONFIG__SS_RESETVALUE 0x0
#define DEVCONFIG__SP_L 3
#define DEVCONFIG__SP_R 3
#define DEVCONFIG__SP 3
#define DEVCONFIG__SP_WIDTH 1
#define DEVCONFIG__SP_RESETVALUE 0x0
#define DEVCONFIG__RWKP_L 2
#define DEVCONFIG__RWKP_R 2
#define DEVCONFIG__RWKP 2
#define DEVCONFIG__RWKP_WIDTH 1
#define DEVCONFIG__RWKP_RESETVALUE 0x0
#define DEVCONFIG__SPD_L 1
#define DEVCONFIG__SPD_R 0
#define DEVCONFIG__SPD_WIDTH 2
#define DEVCONFIG__SPD_RESETVALUE 0x0
#define DEVCONFIG__RESERVED_L 31
#define DEVCONFIG__RESERVED_R 22
#define DEVCONFIG_WIDTH 22
#define DEVCONFIG__WIDTH 22
#define DEVCONFIG_ALL_L 21
#define DEVCONFIG_ALL_R 0
#define DEVCONFIG__ALL_L 21
#define DEVCONFIG__ALL_R 0
#define DEVCONFIG_DATAMASK 0x003fffff
#define DEVCONFIG_RESETVALUE 0x20
#define DEVCTRL 0x47000404
#define DEVCTRL_BASE 0x404
#define DEVCTRL_OFFSET 0x404
#define DEVCTRL__THLEN_L 31
#define DEVCTRL__THLEN_R 24
#define DEVCTRL__THLEN_WIDTH 8
#define DEVCTRL__THLEN_RESETVALUE 0x00
#define DEVCTRL__BRLEN_L 23
#define DEVCTRL__BRLEN_R 16
#define DEVCTRL__BRLEN_WIDTH 8
#define DEVCTRL__BRLEN_RESETVALUE 0x00
#define DEVCTRL__SRX_FLUSH_L 14
#define DEVCTRL__SRX_FLUSH_R 14
#define DEVCTRL__SRX_FLUSH 14
#define DEVCTRL__SRX_FLUSH_WIDTH 1
#define DEVCTRL__SRX_FLUSH_RESETVALUE 0x0
#define DEVCTRL__CSR_DONE_L 13
#define DEVCTRL__CSR_DONE_R 13
#define DEVCTRL__CSR_DONE 13
#define DEVCTRL__CSR_DONE_WIDTH 1
#define DEVCTRL__CSR_DONE_RESETVALUE 0x0
#define DEVCTRL__DEVNAK_L 12
#define DEVCTRL__DEVNAK_R 12
#define DEVCTRL__DEVNAK 12
#define DEVCTRL__DEVNAK_WIDTH 1
#define DEVCTRL__DEVNAK_RESETVALUE 0x0
#define DEVCTRL__SCALE_L 11
#define DEVCTRL__SCALE_R 11
#define DEVCTRL__SCALE 11
#define DEVCTRL__SCALE_WIDTH 1
#define DEVCTRL__SCALE_RESETVALUE 0x0
#define DEVCTRL__SD_L 10
#define DEVCTRL__SD_R 10
#define DEVCTRL__SD 10
#define DEVCTRL__SD_WIDTH 1
#define DEVCTRL__SD_RESETVALUE 0x0
#define DEVCTRL__MODE_L 9
#define DEVCTRL__MODE_R 9
#define DEVCTRL__MODE 9
#define DEVCTRL__MODE_WIDTH 1
#define DEVCTRL__MODE_RESETVALUE 0x0
#define DEVCTRL__BREN_L 8
#define DEVCTRL__BREN_R 8
#define DEVCTRL__BREN 8
#define DEVCTRL__BREN_WIDTH 1
#define DEVCTRL__BREN_RESETVALUE 0x0
#define DEVCTRL__THE_L 7
#define DEVCTRL__THE_R 7
#define DEVCTRL__THE 7
#define DEVCTRL__THE_WIDTH 1
#define DEVCTRL__THE_RESETVALUE 0x0
#define DEVCTRL__BF_L 6
#define DEVCTRL__BF_R 6
#define DEVCTRL__BF 6
#define DEVCTRL__BF_WIDTH 1
#define DEVCTRL__BF_RESETVALUE 0x0
#define DEVCTRL__BE_L 5
#define DEVCTRL__BE_R 5
#define DEVCTRL__BE 5
#define DEVCTRL__BE_WIDTH 1
#define DEVCTRL__BE_RESETVALUE 0x0
#define DEVCTRL__DU_L 4
#define DEVCTRL__DU_R 4
#define DEVCTRL__DU 4
#define DEVCTRL__DU_WIDTH 1
#define DEVCTRL__DU_RESETVALUE 0x0
#define DEVCTRL__TDE_L 3
#define DEVCTRL__TDE_R 3
#define DEVCTRL__TDE 3
#define DEVCTRL__TDE_WIDTH 1
#define DEVCTRL__TDE_RESETVALUE 0x0
#define DEVCTRL__RDE_L 2
#define DEVCTRL__RDE_R 2
#define DEVCTRL__RDE 2
#define DEVCTRL__RDE_WIDTH 1
#define DEVCTRL__RDE_RESETVALUE 0x0
#define DEVCTRL__RES_L 0
#define DEVCTRL__RES_R 0
#define DEVCTRL__RES 0
#define DEVCTRL__RES_WIDTH 1
#define DEVCTRL__RES_RESETVALUE 0x0
#define DEVCTRL_WIDTH 32
#define DEVCTRL__WIDTH 32
#define DEVCTRL_ALL_L 31
#define DEVCTRL_ALL_R 0
#define DEVCTRL__ALL_L 31
#define DEVCTRL__ALL_R 0
#define DEVCTRL_DATAMASK 0xffff7ffd
#define DEVCTRL_RESETVALUE 0x0
#define DEVSTATUS 0x47000408
#define DEVSTATUS_BASE 0x408
#define DEVSTATUS_OFFSET 0x408
#define DEVSTATUS__TS_L 31
#define DEVSTATUS__TS_R 18
#define DEVSTATUS__TS_WIDTH 14
#define DEVSTATUS__TS_RESETVALUE 0x0
#define DEVSTATUS__RMTWKP_STATE_L 17
#define DEVSTATUS__RMTWKP_STATE_R 17
#define DEVSTATUS__RMTWKP_STATE 17
#define DEVSTATUS__RMTWKP_STATE_WIDTH 1
#define DEVSTATUS__RMTWKP_STATE_RESETVALUE 0x0
#define DEVSTATUS__PHY_ERROR_L 16
#define DEVSTATUS__PHY_ERROR_R 16
#define DEVSTATUS__PHY_ERROR 16
#define DEVSTATUS__PHY_ERROR_WIDTH 1
#define DEVSTATUS__PHY_ERROR_RESETVALUE 0x0
#define DEVSTATUS__RXFIFO_EMPTY_L 15
#define DEVSTATUS__RXFIFO_EMPTY_R 15
#define DEVSTATUS__RXFIFO_EMPTY 15
#define DEVSTATUS__RXFIFO_EMPTY_WIDTH 1
#define DEVSTATUS__RXFIFO_EMPTY_RESETVALUE 0x1
#define DEVSTATUS__ENUM_SPD_L 14
#define DEVSTATUS__ENUM_SPD_R 13
#define DEVSTATUS__ENUM_SPD_WIDTH 2
#define DEVSTATUS__ENUM_SPD_RESETVALUE 0x0
#define DEVSTATUS__SUSP_L 12
#define DEVSTATUS__SUSP_R 12
#define DEVSTATUS__SUSP 12
#define DEVSTATUS__SUSP_WIDTH 1
#define DEVSTATUS__SUSP_RESETVALUE 0x0
#define DEVSTATUS__ALT_L 11
#define DEVSTATUS__ALT_R 8
#define DEVSTATUS__ALT_WIDTH 4
#define DEVSTATUS__ALT_RESETVALUE 0x0
#define DEVSTATUS__INTF_L 7
#define DEVSTATUS__INTF_R 4
#define DEVSTATUS__INTF_WIDTH 4
#define DEVSTATUS__INTF_RESETVALUE 0x0
#define DEVSTATUS__CFG_L 3
#define DEVSTATUS__CFG_R 0
#define DEVSTATUS__CFG_WIDTH 4
#define DEVSTATUS__CFG_RESETVALUE 0x0
#define DEVSTATUS_WIDTH 32
#define DEVSTATUS__WIDTH 32
#define DEVSTATUS_ALL_L 31
#define DEVSTATUS_ALL_R 0
#define DEVSTATUS__ALL_L 31
#define DEVSTATUS__ALL_R 0
#define DEVSTATUS_DATAMASK 0xffffffff
#define DEVSTATUS_RESETVALUE 0x8000

#define rng_CTRL 0x45220000
#define rng_CTRL_BASE 0x000
#define rng_CTRL_OFFSET 0x0000
#define rng_CTRL__RNG_COMBLK2_OSC_DIS_L 27
#define rng_CTRL__RNG_COMBLK2_OSC_DIS_R 22
#define rng_CTRL__RNG_COMBLK2_OSC_DIS_WIDTH 6
#define rng_CTRL__RNG_COMBLK2_OSC_DIS_RESETVALUE 0x0
#define rng_CTRL__RNG_COMBLK1_OSC_DIS_L 21
#define rng_CTRL__RNG_COMBLK1_OSC_DIS_R 16
#define rng_CTRL__RNG_COMBLK1_OSC_DIS_WIDTH 6
#define rng_CTRL__RNG_COMBLK1_OSC_DIS_RESETVALUE 0x0
#define rng_CTRL__RNG_JCLK_BYP_DIV_CNT_L 15
#define rng_CTRL__RNG_JCLK_BYP_DIV_CNT_R 8
#define rng_CTRL__RNG_JCLK_BYP_DIV_CNT_WIDTH 8
#define rng_CTRL__RNG_JCLK_BYP_DIV_CNT_RESETVALUE 0x00
#define rng_CTRL__RNG_JCLK_BYP_SRC_L 5
#define rng_CTRL__RNG_JCLK_BYP_SRC_R 5
#define rng_CTRL__RNG_JCLK_BYP_SRC 5
#define rng_CTRL__RNG_JCLK_BYP_SRC_WIDTH 1
#define rng_CTRL__RNG_JCLK_BYP_SRC_RESETVALUE 0x0
#define rng_CTRL__RNG_JCLK_BYP_SEL_L 4
#define rng_CTRL__RNG_JCLK_BYP_SEL_R 4
#define rng_CTRL__RNG_JCLK_BYP_SEL 4
#define rng_CTRL__RNG_JCLK_BYP_SEL_WIDTH 1
#define rng_CTRL__RNG_JCLK_BYP_SEL_RESETVALUE 0x0
#define rng_CTRL__reserved_L 3
#define rng_CTRL__reserved_R 2
#define rng_CTRL__reserved_WIDTH 2
#define rng_CTRL__reserved_RESETVALUE 0x0
#define rng_CTRL__RNG_RBG2X_L 1
#define rng_CTRL__RNG_RBG2X_R 1
#define rng_CTRL__RNG_RBG2X 1
#define rng_CTRL__RNG_RBG2X_WIDTH 1
#define rng_CTRL__RNG_RBG2X_RESETVALUE 0x0
#define rng_CTRL__RNG_RBGEN_L 0
#define rng_CTRL__RNG_RBGEN_R 0
#define rng_CTRL__RNG_RBGEN 0
#define rng_CTRL__RNG_RBGEN_WIDTH 1
#define rng_CTRL__RNG_RBGEN_RESETVALUE 0x0
#define rng_CTRL__RESERVED_L 31
#define rng_CTRL__RESERVED_R 28
#define rng_CTRL_WIDTH 28
#define rng_CTRL__WIDTH 28
#define rng_CTRL_ALL_L 27
#define rng_CTRL_ALL_R 0
#define rng_CTRL__ALL_L 27
#define rng_CTRL__ALL_R 0
#define rng_CTRL_DATAMASK 0x0fffff3f
#define rng_CTRL_RESETVALUE 0x0
#define rng_STATUS 0x45220004
#define rng_STATUS_BASE 0x004
#define rng_STATUS_OFFSET 0x0004
#define rng_STATUS__RND_VAL_L 31
#define rng_STATUS__RND_VAL_R 24
#define rng_STATUS__RND_VAL_WIDTH 8
#define rng_STATUS__RND_VAL_RESETVALUE 0x00
#define rng_STATUS__reserved_L 23
#define rng_STATUS__reserved_R 20
#define rng_STATUS__reserved_WIDTH 4
#define rng_STATUS__reserved_RESETVALUE 0x0
#define rng_STATUS__RNG_WARM_CNT_L 19
#define rng_STATUS__RNG_WARM_CNT_R 0
#define rng_STATUS__RNG_WARM_CNT_WIDTH 20
#define rng_STATUS__RNG_WARM_CNT_RESETVALUE 0x40000
#define rng_STATUS_WIDTH 32
#define rng_STATUS__WIDTH 32
#define rng_STATUS_ALL_L 31
#define rng_STATUS_ALL_R 0
#define rng_STATUS__ALL_L 31
#define rng_STATUS__ALL_R 0
#define rng_STATUS_DATAMASK 0xffffffff
#define rng_STATUS_RESETVALUE 0x40000
#define rng_DATA 0x45220008
#define rng_DATA_BASE 0x008
#define rng_DATA_OFFSET 0x0008
#define rng_DATA__RNG_NUM_L 31
#define rng_DATA__RNG_NUM_R 0
#define rng_DATA__RNG_NUM_WIDTH 32
#define rng_DATA__RNG_NUM_RESETVALUE 0x00000000
#define rng_DATA_WIDTH 32
#define rng_DATA__WIDTH 32
#define rng_DATA_ALL_L 31
#define rng_DATA_ALL_R 0
#define rng_DATA__ALL_L 31
#define rng_DATA__ALL_R 0
#define rng_DATA_DATAMASK 0xffffffff
#define rng_DATA_RESETVALUE 0x0

#endif /* __REGS_H__ */
