OBJS += atomic_c.o
OBJS += device.o
OBJS += irq_manage.o
OBJS += printk.o
OBJS += tick.o
OBJS += util.o

CFLAGS += -include $(MPOS_BASE)/osal/$(CONFIG_RTOS)/irq_map.h

include $(MPOS_BASE)/Makefile.inc
