obj-y += usb.o
obj-y += usbinit.o
obj-y += usbdevice.o
obj-y += usbd_if.o

obj-y += cv/
obj-y += protocol/
obj-y += usbcvclass/

CFLAGS += -I$(MPOS_BASE)/sbis/usbd/include -I$(MPOS_BASE)/sbis/usbd

include $(MPOS_BASE)/Makefile.inc
